// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

const (
	ApiKeyAuthScopes = "apiKeyAuth.Scopes"
	BasicAuthScopes  = "basicAuth.Scopes"
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for APIKeyRole.
const (
	APIKeyRoleAdmin    APIKeyRole = "admin"
	APIKeyRoleOperator APIKeyRole = "operator"
	APIKeyRoleViewer   APIKeyRole = "viewer"
)

// Defines values for ActionConcurrency.
const (
	Allow     ActionConcurrency = "allow"
	Exclusive ActionConcurrency = "exclusive"
	Serialize ActionConcurrency = "serialize"
)

// Defines values for ActionExecutionStatusState.
const (
	ActionExecutionStatusStateFailed    ActionExecutionStatusState = "Failed"
	ActionExecutionStatusStatePending   ActionExecutionStatusState = "Pending"
	ActionExecutionStatusStateRejected  ActionExecutionStatusState = "Rejected"
	ActionExecutionStatusStateRunning   ActionExecutionStatusState = "Running"
	ActionExecutionStatusStateSucceeded ActionExecutionStatusState = "Succeeded"
)

// Defines values for ActionParamType.
const (
	Boolean ActionParamType = "boolean"
	Number  ActionParamType = "number"
	String  ActionParamType = "string"
)

// Defines values for AuthConfigAuthModes.
const (
	Apikey AuthConfigAuthModes = "apikey"
	Basic  AuthConfigAuthModes = "basic"
	None   AuthConfigAuthModes = "none"
	Oidc   AuthConfigAuthModes = "oidc"
)

// Defines values for CreateAPIKeyRequestRole.
const (
	CreateAPIKeyRequestRoleAdmin    CreateAPIKeyRequestRole = "admin"
	CreateAPIKeyRequestRoleOperator CreateAPIKeyRequestRole = "operator"
	CreateAPIKeyRequestRoleViewer   CreateAPIKeyRequestRole = "viewer"
)

// Defines values for GameServerFleetSpecUpdateStrategyType.
const (
	Recreate      GameServerFleetSpecUpdateStrategyType = "Recreate"
	RollingUpdate GameServerFleetSpecUpdateStrategyType = "RollingUpdate"
)

// Defines values for GameServerStatusState.
const (
	GameServerStatusStateError        GameServerStatusState = "Error"
	GameServerStatusStateIdle         GameServerStatusState = "Idle"
	GameServerStatusStateProvisioning GameServerStatusState = "Provisioning"
	GameServerStatusStateRunning      GameServerStatusState = "Running"
	GameServerStatusStateStopped      GameServerStatusState = "Stopped"
)

// Defines values for GameSnapshotStatusState.
const (
	Failed  GameSnapshotStatusState = "Failed"
	Pending GameSnapshotStatusState = "Pending"
	Ready   GameSnapshotStatusState = "Ready"
)

// Defines values for PortProtocol.
const (
	TCP PortProtocol = "TCP"
	UDP PortProtocol = "UDP"
)

// APIKey defines model for APIKey.
type APIKey struct {
	CreatedAt *time.Time  `json:"createdAt,omitempty"`
	CreatedBy *string     `json:"createdBy,omitempty"`
	Name      *string     `json:"name,omitempty"`
	Role      *APIKeyRole `json:"role,omitempty"`
}

// APIKeyRole defines model for APIKey.Role.
type APIKeyRole string

// APIKeyCreated defines model for APIKeyCreated.
type APIKeyCreated struct {
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// Key The API key value (shown once)
	Key     string  `json:"key"`
	Name    string  `json:"name"`
	Role    string  `json:"role"`
	Warning *string `json:"warning,omitempty"`
}

// Action defines model for Action.
type Action struct {
	Concurrency *ActionConcurrency      `json:"concurrency,omitempty"`
	Description *string                 `json:"description,omitempty"`
	Name        *string                 `json:"name,omitempty"`
	Params      *map[string]ActionParam `json:"params,omitempty"`
	Timeout     *string                 `json:"timeout,omitempty"`
}

// ActionConcurrency defines model for Action.Concurrency.
type ActionConcurrency string

// ActionExecution defines model for ActionExecution.
type ActionExecution struct {
	ApiVersion *string     `json:"apiVersion,omitempty"`
	Kind       *string     `json:"kind,omitempty"`
	Metadata   *ObjectMeta `json:"metadata,omitempty"`
	Spec       *struct {
		ActionName *string            `json:"actionName,omitempty"`
		Caller     *string            `json:"caller,omitempty"`
		Params     *map[string]string `json:"params,omitempty"`
		TargetRef  *struct {
			ApiVersion *string `json:"apiVersion,omitempty"`
			Kind       *string `json:"kind,omitempty"`
			Name       *string `json:"name,omitempty"`
			Namespace  *string `json:"namespace,omitempty"`
		} `json:"targetRef,omitempty"`
	} `json:"spec,omitempty"`
	Status *struct {
		CompletedAt *time.Time                  `json:"completedAt,omitempty"`
		Error       *string                     `json:"error,omitempty"`
		Result      *string                     `json:"result,omitempty"`
		StartedAt   *time.Time                  `json:"startedAt,omitempty"`
		State       *ActionExecutionStatusState `json:"state,omitempty"`
	} `json:"status,omitempty"`
}

// ActionExecutionStatusState defines model for ActionExecution.Status.State.
type ActionExecutionStatusState string

// ActionExecutionRef defines model for ActionExecutionRef.
type ActionExecutionRef struct {
	// Name Execution ID
	Name string `json:"name"`
}

// ActionParam defines model for ActionParam.
type ActionParam struct {
	Default  *string          `json:"default,omitempty"`
	Required *bool            `json:"required,omitempty"`
	Type     *ActionParamType `json:"type,omitempty"`
}

// ActionParamType defines model for ActionParam.Type.
type ActionParamType string

// AuthConfig defines model for AuthConfig.
type AuthConfig struct {
	// AuthModes Available authentication modes
	AuthModes []AuthConfigAuthModes `json:"authModes"`

	// BasicEnabled Whether Basic auth is enabled
	BasicEnabled bool `json:"basicEnabled"`

	// OidcIssuer OIDC issuer URL (if OIDC is enabled)
	OidcIssuer *string `json:"oidcIssuer"`
}

// AuthConfigAuthModes defines model for AuthConfig.AuthModes.
type AuthConfigAuthModes string

// CreateAPIKeyRequest defines model for CreateAPIKeyRequest.
type CreateAPIKeyRequest struct {
	// Name Key name
	Name string `json:"name"`

	// Role Role for the key (defaults to the caller's role)
	Role *CreateAPIKeyRequestRole `json:"role,omitempty"`
}

// CreateAPIKeyRequestRole Role for the key (defaults to the caller's role)
type CreateAPIKeyRequestRole string

// Endpoint defines model for Endpoint.
type Endpoint struct {
	Address *string `json:"address,omitempty"`
	Name    *string `json:"name,omitempty"`
	Port    *int    `json:"port,omitempty"`
}

// EnvVar defines model for EnvVar.
type EnvVar struct {
	Default     *string `json:"default,omitempty"`
	Description *string `json:"description,omitempty"`
	Key         *string `json:"key,omitempty"`
	Required    *bool   `json:"required,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// GameProfile defines model for GameProfile.
type GameProfile struct {
	ApiVersion *string          `json:"apiVersion,omitempty"`
	Kind       *string          `json:"kind,omitempty"`
	Metadata   *ObjectMeta      `json:"metadata,omitempty"`
	Spec       *GameProfileSpec `json:"spec,omitempty"`
}

// GameProfileSpec defines model for GameProfileSpec.
type GameProfileSpec struct {
	Actions *[]Action `json:"actions,omitempty"`
	Agent   *struct {
		Image   *string `json:"image,omitempty"`
		Version *string `json:"version,omitempty"`
	} `json:"agent,omitempty"`
	Capabilities *struct {
		Backup              *bool `json:"backup,omitempty"`
		Files               *bool `json:"files,omitempty"`
		RestoreFromSnapshot *bool `json:"restoreFromSnapshot,omitempty"`
		Sftp                *bool `json:"sftp,omitempty"`
	} `json:"capabilities,omitempty"`
	DisplayName *string   `json:"displayName,omitempty"`
	Environment *[]EnvVar `json:"environment,omitempty"`

	// Image Game server container image
	Image         *string `json:"image,omitempty"`
	Observability *struct {
		AgentMetrics *struct {
			Path *string `json:"path,omitempty"`
			Port *int    `json:"port,omitempty"`
		} `json:"agentMetrics,omitempty"`
		ServiceMonitor *struct {
			Enabled  *bool   `json:"enabled,omitempty"`
			Interval *string `json:"interval,omitempty"`
		} `json:"serviceMonitor,omitempty"`
	} `json:"observability,omitempty"`
	Ports     *[]Port `json:"ports,omitempty"`
	Resources *struct {
		Limits *struct {
			Cpu    *string `json:"cpu,omitempty"`
			Memory *string `json:"memory,omitempty"`
		} `json:"limits,omitempty"`
		Requests *struct {
			Cpu    *string `json:"cpu,omitempty"`
			Memory *string `json:"memory,omitempty"`
		} `json:"requests,omitempty"`
	} `json:"resources,omitempty"`
	Storage *struct {
		MountPath   string  `json:"mountPath"`
		SizeDefault *string `json:"sizeDefault,omitempty"`
	} `json:"storage,omitempty"`
}

// GameServer defines model for GameServer.
type GameServer struct {
	ApiVersion *string           `json:"apiVersion,omitempty"`
	Kind       *string           `json:"kind,omitempty"`
	Metadata   *ObjectMeta       `json:"metadata,omitempty"`
	Spec       *GameServerSpec   `json:"spec,omitempty"`
	Status     *GameServerStatus `json:"status,omitempty"`
}

// GameServerFleet defines model for GameServerFleet.
type GameServerFleet struct {
	ApiVersion *string     `json:"apiVersion,omitempty"`
	Kind       *string     `json:"kind,omitempty"`
	Metadata   *ObjectMeta `json:"metadata,omitempty"`
	Spec       *struct {
		PriorityClassName *string `json:"priorityClassName,omitempty"`
		Profile           *string `json:"profile,omitempty"`
		Replicas          *int    `json:"replicas,omitempty"`
		Template          *struct {
			Spec *GameServerSpec `json:"spec,omitempty"`
		} `json:"template,omitempty"`
		TopologySpreadConstraints *[]map[string]interface{} `json:"topologySpreadConstraints,omitempty"`
		UpdateStrategy            *struct {
			RollingUpdate *struct {
				MaxUnavailable *int `json:"maxUnavailable,omitempty"`
			} `json:"rollingUpdate,omitempty"`
			Type *GameServerFleetSpecUpdateStrategyType `json:"type,omitempty"`
		} `json:"updateStrategy,omitempty"`
	} `json:"spec,omitempty"`
	Status *struct {
		AvailableReplicas *int                      `json:"availableReplicas,omitempty"`
		Conditions        *[]map[string]interface{} `json:"conditions,omitempty"`
		ReadyReplicas     *int                      `json:"readyReplicas,omitempty"`
		Replicas          *int                      `json:"replicas,omitempty"`
		UpdatedReplicas   *int                      `json:"updatedReplicas,omitempty"`
	} `json:"status,omitempty"`
}

// GameServerFleetSpecUpdateStrategyType defines model for GameServerFleet.Spec.UpdateStrategy.Type.
type GameServerFleetSpecUpdateStrategyType string

// GameServerSpec defines model for GameServerSpec.
type GameServerSpec struct {
	// Env Environment variables
	Env       *map[string]string `json:"env,omitempty"`
	Lifecycle *struct {
		AutoStart          *bool `json:"autoStart,omitempty"`
		IdleTimeoutSeconds *int  `json:"idleTimeoutSeconds,omitempty"`
	} `json:"lifecycle,omitempty"`
	PriorityClassName *string `json:"priorityClassName,omitempty"`

	// Profile Reference to GameProfile name
	Profile *string      `json:"profile,omitempty"`
	Storage *StorageSpec `json:"storage,omitempty"`
}

// GameServerStatus defines model for GameServerStatus.
type GameServerStatus struct {
	AgentVersion *string                   `json:"agentVersion,omitempty"`
	Conditions   *[]map[string]interface{} `json:"conditions,omitempty"`
	Endpoints    *[]Endpoint               `json:"endpoints,omitempty"`

	// PlayerCapacity Maximum player capacity
	PlayerCapacity *int `json:"playerCapacity,omitempty"`

	// Players Current player count
	Players *int                   `json:"players,omitempty"`
	State   *GameServerStatusState `json:"state,omitempty"`
}

// GameServerStatusState defines model for GameServerStatus.State.
type GameServerStatusState string

// GameSnapshot defines model for GameSnapshot.
type GameSnapshot struct {
	ApiVersion *string     `json:"apiVersion,omitempty"`
	Kind       *string     `json:"kind,omitempty"`
	Metadata   *ObjectMeta `json:"metadata,omitempty"`
	Spec       *struct {
		GameServerRef *string `json:"gameServerRef,omitempty"`
		Retention     *struct {
			Count    *int    `json:"count,omitempty"`
			Duration *string `json:"duration,omitempty"`
		} `json:"retention,omitempty"`

		// Schedule Cron expression for scheduled snapshots
		Schedule *string `json:"schedule,omitempty"`
	} `json:"spec,omitempty"`
	Status *struct {
		ReadyAt *time.Time               `json:"readyAt,omitempty"`
		Size    *string                  `json:"size,omitempty"`
		State   *GameSnapshotStatusState `json:"state,omitempty"`
	} `json:"status,omitempty"`
}

// GameSnapshotStatusState defines model for GameSnapshot.Status.State.
type GameSnapshotStatusState string

// ObjectMeta defines model for ObjectMeta.
type ObjectMeta struct {
	CreationTimestamp *time.Time         `json:"creationTimestamp,omitempty"`
	Labels            *map[string]string `json:"labels,omitempty"`
	Name              *string            `json:"name,omitempty"`
	Namespace         *string            `json:"namespace,omitempty"`
}

// Port defines model for Port.
type Port struct {
	ContainerPort *int          `json:"containerPort,omitempty"`
	Name          *string       `json:"name,omitempty"`
	Protocol      *PortProtocol `json:"protocol,omitempty"`
}

// PortProtocol defines model for Port.Protocol.
type PortProtocol string

// StorageSpec defines model for StorageSpec.
type StorageSpec struct {
	Size        *string `json:"size,omitempty"`
	SnapshotRef *struct {
		Name      *string `json:"name,omitempty"`
		Namespace *string `json:"namespace,omitempty"`
	} `json:"snapshotRef,omitempty"`
	StorageClass *string `json:"storageClass,omitempty"`
}

// Name defines model for Name.
type Name = string

// Namespace defines model for Namespace.
type Namespace = string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ExecuteActionJSONBody defines parameters for ExecuteAction.
type ExecuteActionJSONBody map[string]string

// CreateAPIKeyJSONRequestBody defines body for CreateAPIKey for application/json ContentType.
type CreateAPIKeyJSONRequestBody = CreateAPIKeyRequest

// CreateGameServerJSONRequestBody defines body for CreateGameServer for application/json ContentType.
type CreateGameServerJSONRequestBody = GameServer

// ExecuteActionJSONRequestBody defines body for ExecuteAction for application/json ContentType.
type ExecuteActionJSONRequestBody ExecuteActionJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List API keys
	// (GET /api/v1/apikeys)
	ListAPIKeys(w http.ResponseWriter, r *http.Request)
	// Create API key
	// (POST /api/v1/apikeys)
	CreateAPIKey(w http.ResponseWriter, r *http.Request)
	// Revoke API key
	// (DELETE /api/v1/apikeys/{keyId})
	DeleteAPIKey(w http.ResponseWriter, r *http.Request, keyId string)
	// List fleets
	// (GET /api/v1/gameserverfleets)
	ListGameServerFleets(w http.ResponseWriter, r *http.Request)
	// Get fleet
	// (GET /api/v1/gameserverfleets/{namespace}/{name})
	GetGameServerFleet(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name)
	// List game servers
	// (GET /api/v1/gameservers)
	ListGameServers(w http.ResponseWriter, r *http.Request)
	// Create game server
	// (POST /api/v1/gameservers/{namespace})
	CreateGameServer(w http.ResponseWriter, r *http.Request, namespace string)
	// Delete game server
	// (DELETE /api/v1/gameservers/{namespace}/{name})
	DeleteGameServer(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name)
	// Get game server
	// (GET /api/v1/gameservers/{namespace}/{name})
	GetGameServer(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name)
	// List available actions
	// (GET /api/v1/gameservers/{namespace}/{name}/actions)
	ListActions(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name)
	// Execute action
	// (POST /api/v1/gameservers/{namespace}/{name}/actions/{action})
	ExecuteAction(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name, action string)
	// Console WebSocket stream
	// (GET /api/v1/gameservers/{namespace}/{name}/console)
	GetConsole(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name)
	// Get action execution status
	// (GET /api/v1/gameservers/{namespace}/{name}/executions/{executionId})
	GetActionExecution(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name, executionId string)
	// List snapshots
	// (GET /api/v1/gameservers/{namespace}/{name}/snapshots)
	ListSnapshots(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name)
	// Create snapshot
	// (POST /api/v1/gameservers/{namespace}/{name}/snapshots)
	CreateSnapshot(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name)
	// List profiles
	// (GET /api/v1/profiles)
	ListProfiles(w http.ResponseWriter, r *http.Request)
	// Get profile
	// (GET /api/v1/profiles/{name})
	GetProfile(w http.ResponseWriter, r *http.Request, name string)
	// Auth configuration discovery
	// (GET /auth/config)
	GetAuthConfig(w http.ResponseWriter, r *http.Request)
	// Liveness probe
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// Readiness probe
	// (GET /readyz)
	GetReadyz(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List API keys
// (GET /api/v1/apikeys)
func (_ Unimplemented) ListAPIKeys(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create API key
// (POST /api/v1/apikeys)
func (_ Unimplemented) CreateAPIKey(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Revoke API key
// (DELETE /api/v1/apikeys/{keyId})
func (_ Unimplemented) DeleteAPIKey(w http.ResponseWriter, r *http.Request, keyId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List fleets
// (GET /api/v1/gameserverfleets)
func (_ Unimplemented) ListGameServerFleets(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get fleet
// (GET /api/v1/gameserverfleets/{namespace}/{name})
func (_ Unimplemented) GetGameServerFleet(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List game servers
// (GET /api/v1/gameservers)
func (_ Unimplemented) ListGameServers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create game server
// (POST /api/v1/gameservers/{namespace})
func (_ Unimplemented) CreateGameServer(w http.ResponseWriter, r *http.Request, namespace string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete game server
// (DELETE /api/v1/gameservers/{namespace}/{name})
func (_ Unimplemented) DeleteGameServer(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get game server
// (GET /api/v1/gameservers/{namespace}/{name})
func (_ Unimplemented) GetGameServer(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List available actions
// (GET /api/v1/gameservers/{namespace}/{name}/actions)
func (_ Unimplemented) ListActions(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Execute action
// (POST /api/v1/gameservers/{namespace}/{name}/actions/{action})
func (_ Unimplemented) ExecuteAction(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name, action string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Console WebSocket stream
// (GET /api/v1/gameservers/{namespace}/{name}/console)
func (_ Unimplemented) GetConsole(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get action execution status
// (GET /api/v1/gameservers/{namespace}/{name}/executions/{executionId})
func (_ Unimplemented) GetActionExecution(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name, executionId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List snapshots
// (GET /api/v1/gameservers/{namespace}/{name}/snapshots)
func (_ Unimplemented) ListSnapshots(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create snapshot
// (POST /api/v1/gameservers/{namespace}/{name}/snapshots)
func (_ Unimplemented) CreateSnapshot(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List profiles
// (GET /api/v1/profiles)
func (_ Unimplemented) ListProfiles(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get profile
// (GET /api/v1/profiles/{name})
func (_ Unimplemented) GetProfile(w http.ResponseWriter, r *http.Request, name string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Auth configuration discovery
// (GET /auth/config)
func (_ Unimplemented) GetAuthConfig(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Liveness probe
// (GET /healthz)
func (_ Unimplemented) GetHealthz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Readiness probe
// (GET /readyz)
func (_ Unimplemented) GetReadyz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListAPIKeys operation middleware
func (siw *ServerInterfaceWrapper) ListAPIKeys(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAPIKeys(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAPIKey operation middleware
func (siw *ServerInterfaceWrapper) CreateAPIKey(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAPIKey(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAPIKey operation middleware
func (siw *ServerInterfaceWrapper) DeleteAPIKey(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "keyId" -------------
	var keyId string

	err = runtime.BindStyledParameterWithOptions("simple", "keyId", chi.URLParam(r, "keyId"), &keyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "keyId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAPIKey(w, r, keyId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListGameServerFleets operation middleware
func (siw *ServerInterfaceWrapper) ListGameServerFleets(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListGameServerFleets(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGameServerFleet operation middleware
func (siw *ServerInterfaceWrapper) GetGameServerFleet(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace Namespace

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", chi.URLParam(r, "namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name Name

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGameServerFleet(w, r, namespace, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListGameServers operation middleware
func (siw *ServerInterfaceWrapper) ListGameServers(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListGameServers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateGameServer operation middleware
func (siw *ServerInterfaceWrapper) CreateGameServer(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", chi.URLParam(r, "namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateGameServer(w, r, namespace)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteGameServer operation middleware
func (siw *ServerInterfaceWrapper) DeleteGameServer(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace Namespace

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", chi.URLParam(r, "namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name Name

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteGameServer(w, r, namespace, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGameServer operation middleware
func (siw *ServerInterfaceWrapper) GetGameServer(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace Namespace

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", chi.URLParam(r, "namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name Name

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGameServer(w, r, namespace, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListActions operation middleware
func (siw *ServerInterfaceWrapper) ListActions(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace Namespace

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", chi.URLParam(r, "namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name Name

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListActions(w, r, namespace, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExecuteAction operation middleware
func (siw *ServerInterfaceWrapper) ExecuteAction(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace Namespace

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", chi.URLParam(r, "namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name Name

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// ------------- Path parameter "action" -------------
	var action string

	err = runtime.BindStyledParameterWithOptions("simple", "action", chi.URLParam(r, "action"), &action, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "action", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExecuteAction(w, r, namespace, name, action)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetConsole operation middleware
func (siw *ServerInterfaceWrapper) GetConsole(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace Namespace

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", chi.URLParam(r, "namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name Name

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetConsole(w, r, namespace, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetActionExecution operation middleware
func (siw *ServerInterfaceWrapper) GetActionExecution(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace Namespace

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", chi.URLParam(r, "namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name Name

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// ------------- Path parameter "executionId" -------------
	var executionId string

	err = runtime.BindStyledParameterWithOptions("simple", "executionId", chi.URLParam(r, "executionId"), &executionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "executionId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetActionExecution(w, r, namespace, name, executionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSnapshots operation middleware
func (siw *ServerInterfaceWrapper) ListSnapshots(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace Namespace

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", chi.URLParam(r, "namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name Name

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSnapshots(w, r, namespace, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSnapshot operation middleware
func (siw *ServerInterfaceWrapper) CreateSnapshot(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace Namespace

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", chi.URLParam(r, "namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name Name

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSnapshot(w, r, namespace, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProfiles operation middleware
func (siw *ServerInterfaceWrapper) ListProfiles(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProfiles(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProfile operation middleware
func (siw *ServerInterfaceWrapper) GetProfile(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProfile(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthConfig operation middleware
func (siw *ServerInterfaceWrapper) GetAuthConfig(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadyz operation middleware
func (siw *ServerInterfaceWrapper) GetReadyz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadyz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/apikeys", wrapper.ListAPIKeys)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/apikeys", wrapper.CreateAPIKey)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/apikeys/{keyId}", wrapper.DeleteAPIKey)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/gameserverfleets", wrapper.ListGameServerFleets)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/gameserverfleets/{namespace}/{name}", wrapper.GetGameServerFleet)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/gameservers", wrapper.ListGameServers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/gameservers/{namespace}", wrapper.CreateGameServer)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/gameservers/{namespace}/{name}", wrapper.DeleteGameServer)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/gameservers/{namespace}/{name}", wrapper.GetGameServer)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/gameservers/{namespace}/{name}/actions", wrapper.ListActions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/gameservers/{namespace}/{name}/actions/{action}", wrapper.ExecuteAction)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/gameservers/{namespace}/{name}/console", wrapper.GetConsole)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/gameservers/{namespace}/{name}/executions/{executionId}", wrapper.GetActionExecution)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/gameservers/{namespace}/{name}/snapshots", wrapper.ListSnapshots)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/gameservers/{namespace}/{name}/snapshots", wrapper.CreateSnapshot)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/profiles", wrapper.ListProfiles)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/profiles/{name}", wrapper.GetProfile)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/config", wrapper.GetAuthConfig)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealthz)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/readyz", wrapper.GetReadyz)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xc+3LbNpd/FSx3Z9bJ0pKTZqcd9y/HudRNk2ispN0Z27OCwCMRNQmwAChb8Wjme4jv",
	"Cb8n+QYX3kRQomzFaftXZBI4ODjXHw4OcxcQnmacAVMyOL4LMixwCgqE+esDTkH/S1lwHGRYxUEYMPPM",
	"/hMGAv7IqYAoOFYihzCQJIYU6zlqmelxUgnK5sFqFRpqMsNkE0n7fhe6Kz1YZpxJMDy/xNE5/JGDVPov",
	"wpkCZn7iLEsowYpyNvxdcqafVWT/S8AsOA7+c1jJY2jfyuFrIbiwS0UgiaCZJhIcB2dsgRMaIeEWXIXB",
	"Gy6mNIqAPcbqMp/NKKHAFMpApFRKypnUbHzg6g3PWfT1uTgHyXNBADGu0MysuQqDzwznKuaCfoFH4OEk",
	"VzEw5aii0nj0SDdZ0z4Znb2DpTFzwTMQilqTIQKwgujEsDfjIsUqOA4irOBQUWPma0YXFlNeLj0mWRi0",
	"54XgiXkBLE+D44tgQeEGRBAGmh2suP6Jo5Sy4Cr0eJB7wqe/AzHWZnd0apnZy8aurYCa8v0UAzoZnaFr",
	"WKIFTnJABzLmNwxxRuCJj8xWCbRe3GDB9E9v6KjCwUUZeTQhy++VTzLE8t4SCWckFwIYcfuc4TzRUsFJ",
	"wm+CsFSNBEFxQr/oReCWJLmkC/3bjrvy7Lkhs12swgRdwx2OIqrn42TU4HqTV9idjjSNwGcjWtM8NyYA",
	"tzjNtPyD/02DfgZmiL++BZL75Ykz+isI2bXna2pjULXyOkWPIFNQOMJqazz4aNh8DwrrWTID4uHPLPeh",
	"S/QEJwmIe2qlNaUteyzmoM71Fu4puP5WxOrpdatqfdxKhVUufT6jdbdjIAETrL0hAKRxOc8rqbDYcR3N",
	"dCOmjoBF+l0YnOeM2V/jnBCACKIgDN5gmpgf56A3DlGvWNvDObxqLtTVDKjlHHT2yuuIrYDXHeOs57cW",
	"LiObVwMF9fLllPMEMKusuBKomxcGLE+nJlsVg3smqVzFp5zN6LwRCe4CDRHe80jzexFMsaREZ0Ia6X9w",
	"Rl1oNy9eMzxNKjioB51JmWvXDWKlMnk8HGpyg++v54Ln2YDwdCgAJ6kcppRhxY1LNz2wWn5dPycLTBO9",
	"IsJNaJGa8WFAFdjYUAiJcabNs3MXXbECC4GX+u/mNtcZ+i0GFYNAL/UowxSiEoEbHnq0WBfROrWPZ69O",
	"ETUv0efzX9ABnSH3rKCps3rpgLmgRv2JkUmhhM1WW0l3bW8+S7YIxqKZGnrv40rvYIkcJOgEG2uIlSeA",
	"ZlwgFYOBNAfOVyRS3Dy0WeG/JdIEntRAwY54rZcXv2ZRxinzbBhHkQApdwQTXNSdnjIFcxB+z3zNFr9i",
	"sVvs2IZyHIDcKeZ4eSvyR5O1rrSyJm07zCfutziFkeAzak3jgWimTm3vSGbTjNrCYz3cK8P1QR3oyPws",
	"I9p2rOkLX3gOPhOmKZ777XTRKWffTgjO8JQmtKDbXGWKyXWe+bOZ3rz0vxIgFRfwRvB0zHAmY678A+VM",
	"ZX3tNqIyS/CyE3ECW1DBWerE1Uvszk89Yi/l2wxxWvFIgliAQProjSkDgexgj5nyqR5rBew5Hxvdvgcl",
	"KPEI3xRxHhqJ9PqUwHvOqPK6fZUY2+rRlMUCJ/cGvprT/k4w0vvy6EK4SohHRglNqfIh6yz3ii6FlItl",
	"T99w1aevQ95/TuDCmV1zvZTnTI267EHSL/CqM7OsBfCK1FUvnrTFj43Bb4vqVfAukvjAIsQB5cPFM29R",
	"xBv33XKPHvbtujbq1w9tPefZ8VuE+CYBUHvKj3WKX/m0nwnKBVXL0wRL2RmCsyr9e2CKqU5KX+AKAwVp",
	"lrjzZnPl+yjPWzHgGU/4fDnOBODolDOpBKZsLTy1p63FojzTh+axEljB3BPSBU8SyuafzTCPI+PbzwwX",
	"h6C+QXz94HjeWEQfuG1B8t4H7q4CRcnp+UbtEc5sIWdHYWpNLDeT3mw2VhvRJhKrHaOcH88BW+xUsFqr",
	"SlTQBC2woFqiMvCwkdAZkCXxIuhc8bHCogNJ0SiBT7YgOQatD9nXuHZ27fVrihkIYAT0Ga+GizvPjrUk",
	"t8mnx3bYZgzeiLx+eLUprN7XbsGdLOUOQNOdRT3UNKoFcYozTBxKbEr4Pb6laZ4iOw6RYmDocQg7xlN4",
	"OTW1eVUS0SjAS6Fd9hN8QbUI12t/Z5E5m40VzzJTK3m9djbchK2M9mpng32kw4LcV86F89LwXGHSk+sU",
	"sK5rkpwpfzCLcoFVC0t9//wo7neloPcQ5T4fPRWcIbjNBJiLTFOjKUZHSDq5yZ7LdHibCeY7FZjpF+gq",
	"VndWnvUiVa35vvmupmb/3R7lTEdTqXCa9d9RgqeQPPBmY0/XEGEwcqfE1jWdPbSOOg6RmypggitOeNK8",
	"3/t0OqoV8uxfn1+NesaBephvYz9nIZU3PD96S7225Gx441XBg0XqUpfJlH0PeRJIrtPrWEeYMrq9g+VJ",
	"bo9zTVf9BeaYLBFOKJbGT4vr4Wa9/EeUCZ140eTEtQOYx8foJWABYhKEthEkBhyZo5RrBfm/w5PR2eE7",
	"qGUPy01ZKfezVZXHazX7g4QTnKAIFpDwzKAbzpLlk8A1BxiI4ur2brFYqcwsZdj0r2UK5j//9gkpfg02",
	"WMV5ipkMERcII3uoLAVzMLEP/n8wGEye6OGXLMUkpqyoN8sBmpQbnyAqESYEMgURwhJhlHTIXA4uWWMv",
	"hun1zaxMoWTGS+8iqjK64Pt36K3geRaEQS6S2qVK7T6lDRjPX48/GS40NylmeE7ZHM2r4pMM0Uyf+2SI",
	"HDKTIcKsFswHl+wkSVAJVVDOIm0vQ5zR4eLZpGjmWFcq3GrRoJsYhGk9gWhwyS7Zp5hKFHGSGzVTacr5",
	"T5+6FhU+Q0rkKn76tKz/a+61OAQm6pIdSAA0iTiRQyxITBUQlQvQzBwSzhY2XcpBGk2eDJDNrkjwXIFE",
	"WACaAwN95Iou2UzwFFH1I4KIKrOUTtNoRoVUof6bIQHFeKtBRZWJHu+t5ZxqtniCRglmhtGgVjUNng2O",
	"BkemeJcBwxkNjoPvBkeD74LQVOSMBzshDu01lEUF9li/5s1UKoSTpLQodENVzHOFpD6yKdv0IdGBueso",
	"vcfWTyhnZ5EjYm9wZLDWk/X86GinJqB+tWjbzdNCqu32ILM9Pit3p+e8OHrWtUDJ+rDRxWQmfbd9UtUB",
	"ZuJqnqZYLAsuShbCQOG5ufjUj4zQrkwlUnr089aZCcKIwU0VUjapo36lFpRFwpc8Wu6tH8t3a7dqFvKU",
	"yGHVsoZne2Oh2QDlaw1zsnKtUOig6mGqtzAZ5R5tV26tu/CbGJHdaWEBfitaheuOP7y7huVZtLKWlYDy",
	"gO9X5vlQwIJfA8Ksn5XZWaWV1dtHL7xNnoaRnRo8r1rm88JzYe+YtexHj6YcPePF9hllO2ZTm+dW2H21",
	"qROrzas2qW6P52vlV40oBJfSvCtRpfSG8vWpjxLT18vFOwR3J5L7Kb4dqGfFpguVOClsVMjwrhTqyv5e",
	"deroLSiEDSagM0pQu1DeVMlbUO0ha+7m23E1ZFj1X6/CXoMDj+8d7S10t3Td1q15gSJQmCbyoc6mBT4r",
	"LiF6KXUnB7ufbz22W+3iUXUcvze/ahCtFFGXSJc26t5lTs9erOQypEVKFVlEWQnC6YxCVOmoD45q3Pdt",
	"z3L3+5Th6uvAtLr2Hxedra+8oUmhQHB/LRxWs+YHGHMtVWxGZwjXLboHMNtkto+RLV5sbk2xu/2roDWn",
	"gz46D3fM+Wi6rMUjzKLiWmoDCPj75P9twWGPAGCvDjustc9tgAl2ECovqU3tCddZQVMsIUKcIapkUSnz",
	"F1jcin8B3T+oobAblVRiLKT/QLOwSmpRrR3G3JN7WMbwzv7YgFfspwDmxG3HajNoWsdB0aj0Px3B3tFw",
	"wnwE2wi9qAcX6z8K5Ol9d1X74iAFKc2lfvATJAl318zyPzxXXO0vS/dat2p/OuIrXhFX6y6+FnHfx3wb",
	"zFNaaqHmhzgI4Uy67nxv6PyczQWOwLTkY/QbTMecXINChDMGxAlDAE4pm6OELgA5iojnKsuVTqKXzF6g",
	"6CHFW8LTFLNIDtCnGJCzB1RcGSIqUQQzyiBClF0ydxUwB6YO3f2R3o8jdlhMG6TRBB1oA4rQz+OPH9BM",
	"+4s8vmQkMV/nSmCRRBNBOJsMJxll80lYeLd7l/D5ZGhGHBaqmAwn9hZ7MpyYhvbJk8ElO7fOJVERFcxX",
	"CogLFNN5DMLeJbSAw6kT+DfIHM+sqTYVPL6hisRaNSMnRYn+9Y9/1lRt9YtAKjxNqIz/3MeDhyUhp53W",
	"7mteVihwFy8rI4cc3pW/XSG4E6GaY7KxO5Nvy7wEtW82W+bV/qzzGyWh2jYfWGY++lrRvleo3yPoxZ40",
	"ovKHQpyqH2cj/C2HtWGvF+GOa20+fw+M22j62gHpVgL2ANZGN5TTYiW67qvEsjxWEPCcRrbiTUuk1sj2",
	"DRS15ypVqZ+2Pop3zSLVN6o4yVr3oEftNfctGi76FbFdO6xEByTJpQJxKAnP7HegbSctRj9a9br4xm7X",
	"8nUphH3Vr7Nq54X8S2F4xX+Pe6BRRwHgLajqVb8i9J8mBTaU2FZa0Y29x6xXlVG6FJWrWEN592G6Vzvn",
	"oHLBbBsR3vhRuKnaWWquQXbg2pGK3iZ9uMjyaUKJGZtLiNB0aUh/PjPnnFzxw4KEXaUDzNc+qf+asKVa",
	"peM/3WluuNFIGBxfXNVV0h6OIioJX4Bo3HznKnb6iQEnKv6yVTfPj47Qx3eIzuy3265rKjNdU1QiUXaC",
	"t8T4k1thqwwV3KphlmC6Jr3at2TXnrbklsxO15nD+ui6UW6/0AUwkKYsOK1bs2Xeycp0NT9cVJqKtkQD",
	"BFD5YaFHdOd2wW8nOcPrRslpFukW0TWn3zUaPi+uNDypdZvaB/W22IsrHTTL2+KLVopd7zxt9FceD4em",
	"NTXmUh3/cPTDkcE5jsl1UiMbOaxTIBIDuZZVrHc70vxt/K+x6i7nppqdtCfWC/Dl9z62yRPcThyBevV8",
	"Mx3PQbJgoqzlbppfYlYfGxUM2kzE9AB4KbwpWki8010+8c4cVTCjjbJqtamyZFVNLY71HtW5nibfgmWD",
	"0Opq9e8AAAD//yjiJxfETwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
