// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

const (
	ApiKeyAuthScopes = "apiKeyAuth.Scopes"
	BasicAuthScopes  = "basicAuth.Scopes"
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for APIKeyRole.
const (
	APIKeyRoleAdmin    APIKeyRole = "admin"
	APIKeyRoleOperator APIKeyRole = "operator"
	APIKeyRoleViewer   APIKeyRole = "viewer"
)

// Defines values for ActionConcurrency.
const (
	Allow     ActionConcurrency = "allow"
	Exclusive ActionConcurrency = "exclusive"
	Serialize ActionConcurrency = "serialize"
)

// Defines values for ActionExecutionStatusState.
const (
	ActionExecutionStatusStateFailed    ActionExecutionStatusState = "Failed"
	ActionExecutionStatusStatePending   ActionExecutionStatusState = "Pending"
	ActionExecutionStatusStateRejected  ActionExecutionStatusState = "Rejected"
	ActionExecutionStatusStateRunning   ActionExecutionStatusState = "Running"
	ActionExecutionStatusStateSucceeded ActionExecutionStatusState = "Succeeded"
)

// Defines values for ActionParamType.
const (
	Boolean ActionParamType = "boolean"
	Number  ActionParamType = "number"
	String  ActionParamType = "string"
)

// Defines values for AuthConfigAuthModes.
const (
	Apikey AuthConfigAuthModes = "apikey"
	Basic  AuthConfigAuthModes = "basic"
	None   AuthConfigAuthModes = "none"
	Oidc   AuthConfigAuthModes = "oidc"
)

// Defines values for CreateAPIKeyRequestRole.
const (
	CreateAPIKeyRequestRoleAdmin    CreateAPIKeyRequestRole = "admin"
	CreateAPIKeyRequestRoleOperator CreateAPIKeyRequestRole = "operator"
	CreateAPIKeyRequestRoleViewer   CreateAPIKeyRequestRole = "viewer"
)

// Defines values for GameServerFleetSpecUpdateStrategyType.
const (
	Recreate      GameServerFleetSpecUpdateStrategyType = "Recreate"
	RollingUpdate GameServerFleetSpecUpdateStrategyType = "RollingUpdate"
)

// Defines values for GameServerStatusState.
const (
	GameServerStatusStateError        GameServerStatusState = "Error"
	GameServerStatusStateIdle         GameServerStatusState = "Idle"
	GameServerStatusStateProvisioning GameServerStatusState = "Provisioning"
	GameServerStatusStateRunning      GameServerStatusState = "Running"
	GameServerStatusStateStopped      GameServerStatusState = "Stopped"
)

// Defines values for GameSnapshotStatusState.
const (
	Failed  GameSnapshotStatusState = "Failed"
	Pending GameSnapshotStatusState = "Pending"
	Ready   GameSnapshotStatusState = "Ready"
)

// Defines values for PortProtocol.
const (
	TCP PortProtocol = "TCP"
	UDP PortProtocol = "UDP"
)

// APIKey defines model for APIKey.
type APIKey struct {
	CreatedAt *time.Time  `json:"createdAt,omitempty"`
	CreatedBy *string     `json:"createdBy,omitempty"`
	Name      *string     `json:"name,omitempty"`
	Role      *APIKeyRole `json:"role,omitempty"`
}

// APIKeyRole defines model for APIKey.Role.
type APIKeyRole string

// APIKeyCreated defines model for APIKeyCreated.
type APIKeyCreated struct {
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// Key The API key value (shown once)
	Key     string  `json:"key"`
	Name    string  `json:"name"`
	Role    string  `json:"role"`
	Warning *string `json:"warning,omitempty"`
}

// Action defines model for Action.
type Action struct {
	Concurrency *ActionConcurrency      `json:"concurrency,omitempty"`
	Description *string                 `json:"description,omitempty"`
	Name        *string                 `json:"name,omitempty"`
	Params      *map[string]ActionParam `json:"params,omitempty"`
	Timeout     *string                 `json:"timeout,omitempty"`
}

// ActionConcurrency defines model for Action.Concurrency.
type ActionConcurrency string

// ActionExecution defines model for ActionExecution.
type ActionExecution struct {
	ApiVersion *string     `json:"apiVersion,omitempty"`
	Kind       *string     `json:"kind,omitempty"`
	Metadata   *ObjectMeta `json:"metadata,omitempty"`
	Spec       *struct {
		ActionName *string            `json:"actionName,omitempty"`
		Caller     *string            `json:"caller,omitempty"`
		Params     *map[string]string `json:"params,omitempty"`
		TargetRef  *struct {
			ApiVersion *string `json:"apiVersion,omitempty"`
			Kind       *string `json:"kind,omitempty"`
			Name       *string `json:"name,omitempty"`
			Namespace  *string `json:"namespace,omitempty"`
		} `json:"targetRef,omitempty"`
	} `json:"spec,omitempty"`
	Status *struct {
		CompletedAt *time.Time                  `json:"completedAt,omitempty"`
		Error       *string                     `json:"error,omitempty"`
		Result      *string                     `json:"result,omitempty"`
		StartedAt   *time.Time                  `json:"startedAt,omitempty"`
		State       *ActionExecutionStatusState `json:"state,omitempty"`
	} `json:"status,omitempty"`
}

// ActionExecutionStatusState defines model for ActionExecution.Status.State.
type ActionExecutionStatusState string

// ActionExecutionRef defines model for ActionExecutionRef.
type ActionExecutionRef struct {
	// Name Execution ID
	Name string `json:"name"`
}

// ActionParam defines model for ActionParam.
type ActionParam struct {
	Default  *string          `json:"default,omitempty"`
	Required *bool            `json:"required,omitempty"`
	Type     *ActionParamType `json:"type,omitempty"`
}

// ActionParamType defines model for ActionParam.Type.
type ActionParamType string

// AuthConfig defines model for AuthConfig.
type AuthConfig struct {
	// AuthModes Available authentication modes
	AuthModes []AuthConfigAuthModes `json:"authModes"`

	// BasicEnabled Whether Basic auth is enabled
	BasicEnabled bool `json:"basicEnabled"`

	// OidcIssuer OIDC issuer URL (if OIDC is enabled)
	OidcIssuer *string `json:"oidcIssuer"`
}

// AuthConfigAuthModes defines model for AuthConfig.AuthModes.
type AuthConfigAuthModes string

// CreateAPIKeyRequest defines model for CreateAPIKeyRequest.
type CreateAPIKeyRequest struct {
	// Name Key name
	Name string `json:"name"`

	// Role Role for the key (defaults to the caller's role)
	Role *CreateAPIKeyRequestRole `json:"role,omitempty"`
}

// CreateAPIKeyRequestRole Role for the key (defaults to the caller's role)
type CreateAPIKeyRequestRole string

// Endpoint defines model for Endpoint.
type Endpoint struct {
	Address *string `json:"address,omitempty"`
	Name    *string `json:"name,omitempty"`
	Port    *int    `json:"port,omitempty"`
}

// EnvVar defines model for EnvVar.
type EnvVar struct {
	Default     *string `json:"default,omitempty"`
	Description *string `json:"description,omitempty"`
	Key         *string `json:"key,omitempty"`
	Required    *bool   `json:"required,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// GameProfile defines model for GameProfile.
type GameProfile struct {
	ApiVersion *string          `json:"apiVersion,omitempty"`
	Kind       *string          `json:"kind,omitempty"`
	Metadata   *ObjectMeta      `json:"metadata,omitempty"`
	Spec       *GameProfileSpec `json:"spec,omitempty"`
}

// GameProfileSpec defines model for GameProfileSpec.
type GameProfileSpec struct {
	Actions *[]Action `json:"actions,omitempty"`
	Agent   *struct {
		Image   *string `json:"image,omitempty"`
		Version *string `json:"version,omitempty"`
	} `json:"agent,omitempty"`
	Capabilities *struct {
		Backup              *bool `json:"backup,omitempty"`
		Files               *bool `json:"files,omitempty"`
		RestoreFromSnapshot *bool `json:"restoreFromSnapshot,omitempty"`
		Sftp                *bool `json:"sftp,omitempty"`
	} `json:"capabilities,omitempty"`
	DisplayName *string   `json:"displayName,omitempty"`
	Environment *[]EnvVar `json:"environment,omitempty"`

	// Image Game server container image
	Image         *string `json:"image,omitempty"`
	Observability *struct {
		AgentMetrics *struct {
			Path *string `json:"path,omitempty"`
			Port *int    `json:"port,omitempty"`
		} `json:"agentMetrics,omitempty"`
		ServiceMonitor *struct {
			Enabled  *bool   `json:"enabled,omitempty"`
			Interval *string `json:"interval,omitempty"`
		} `json:"serviceMonitor,omitempty"`
	} `json:"observability,omitempty"`
	Ports     *[]Port `json:"ports,omitempty"`
	Resources *struct {
		Limits *struct {
			Cpu    *string `json:"cpu,omitempty"`
			Memory *string `json:"memory,omitempty"`
		} `json:"limits,omitempty"`
		Requests *struct {
			Cpu    *string `json:"cpu,omitempty"`
			Memory *string `json:"memory,omitempty"`
		} `json:"requests,omitempty"`
	} `json:"resources,omitempty"`
	Storage *struct {
		MountPath   string  `json:"mountPath"`
		SizeDefault *string `json:"sizeDefault,omitempty"`
	} `json:"storage,omitempty"`
}

// GameServer defines model for GameServer.
type GameServer struct {
	ApiVersion *string           `json:"apiVersion,omitempty"`
	Kind       *string           `json:"kind,omitempty"`
	Metadata   *ObjectMeta       `json:"metadata,omitempty"`
	Spec       *GameServerSpec   `json:"spec,omitempty"`
	Status     *GameServerStatus `json:"status,omitempty"`
}

// GameServerFleet defines model for GameServerFleet.
type GameServerFleet struct {
	ApiVersion *string     `json:"apiVersion,omitempty"`
	Kind       *string     `json:"kind,omitempty"`
	Metadata   *ObjectMeta `json:"metadata,omitempty"`
	Spec       *struct {
		PriorityClassName *string `json:"priorityClassName,omitempty"`
		Profile           *string `json:"profile,omitempty"`
		Replicas          *int    `json:"replicas,omitempty"`
		Template          *struct {
			Spec *GameServerSpec `json:"spec,omitempty"`
		} `json:"template,omitempty"`
		TopologySpreadConstraints *[]map[string]interface{} `json:"topologySpreadConstraints,omitempty"`
		UpdateStrategy            *struct {
			RollingUpdate *struct {
				MaxUnavailable *int `json:"maxUnavailable,omitempty"`
			} `json:"rollingUpdate,omitempty"`
			Type *GameServerFleetSpecUpdateStrategyType `json:"type,omitempty"`
		} `json:"updateStrategy,omitempty"`
	} `json:"spec,omitempty"`
	Status *struct {
		AvailableReplicas *int                      `json:"availableReplicas,omitempty"`
		Conditions        *[]map[string]interface{} `json:"conditions,omitempty"`
		ReadyReplicas     *int                      `json:"readyReplicas,omitempty"`
		Replicas          *int                      `json:"replicas,omitempty"`
		UpdatedReplicas   *int                      `json:"updatedReplicas,omitempty"`
	} `json:"status,omitempty"`
}

// GameServerFleetSpecUpdateStrategyType defines model for GameServerFleet.Spec.UpdateStrategy.Type.
type GameServerFleetSpecUpdateStrategyType string

// GameServerSpec defines model for GameServerSpec.
type GameServerSpec struct {
	// Env Environment variables
	Env       *map[string]string `json:"env,omitempty"`
	Lifecycle *struct {
		AutoStart          *bool `json:"autoStart,omitempty"`
		IdleTimeoutSeconds *int  `json:"idleTimeoutSeconds,omitempty"`
	} `json:"lifecycle,omitempty"`

	// LoadBalancerIP Pin a specific external IP for the game server's LoadBalancer service
	LoadBalancerIP    *string `json:"loadBalancerIP,omitempty"`
	PriorityClassName *string `json:"priorityClassName,omitempty"`

	// Profile Reference to GameProfile name
	Profile *string      `json:"profile,omitempty"`
	Storage *StorageSpec `json:"storage,omitempty"`
}

// GameServerStatus defines model for GameServerStatus.
type GameServerStatus struct {
	AgentVersion *string                   `json:"agentVersion,omitempty"`
	Conditions   *[]map[string]interface{} `json:"conditions,omitempty"`
	Endpoints    *[]Endpoint               `json:"endpoints,omitempty"`

	// PlayerCapacity Maximum player capacity
	PlayerCapacity *int `json:"playerCapacity,omitempty"`

	// Players Current player count
	Players *int                   `json:"players,omitempty"`
	State   *GameServerStatusState `json:"state,omitempty"`
}

// GameServerStatusState defines model for GameServerStatus.State.
type GameServerStatusState string

// GameSnapshot defines model for GameSnapshot.
type GameSnapshot struct {
	ApiVersion *string     `json:"apiVersion,omitempty"`
	Kind       *string     `json:"kind,omitempty"`
	Metadata   *ObjectMeta `json:"metadata,omitempty"`
	Spec       *struct {
		GameServerRef *string `json:"gameServerRef,omitempty"`
		Retention     *struct {
			Count    *int    `json:"count,omitempty"`
			Duration *string `json:"duration,omitempty"`
		} `json:"retention,omitempty"`

		// Schedule Cron expression for scheduled snapshots
		Schedule *string `json:"schedule,omitempty"`
	} `json:"spec,omitempty"`
	Status *struct {
		ReadyAt *time.Time               `json:"readyAt,omitempty"`
		Size    *string                  `json:"size,omitempty"`
		State   *GameSnapshotStatusState `json:"state,omitempty"`
	} `json:"status,omitempty"`
}

// GameSnapshotStatusState defines model for GameSnapshot.Status.State.
type GameSnapshotStatusState string

// ObjectMeta defines model for ObjectMeta.
type ObjectMeta struct {
	CreationTimestamp *time.Time         `json:"creationTimestamp,omitempty"`
	Labels            *map[string]string `json:"labels,omitempty"`
	Name              *string            `json:"name,omitempty"`
	Namespace         *string            `json:"namespace,omitempty"`
}

// Port defines model for Port.
type Port struct {
	ContainerPort *int `json:"containerPort,omitempty"`

	// Exposed Whether this port is published on the external LoadBalancer service
	Exposed  *bool         `json:"exposed,omitempty"`
	Name     *string       `json:"name,omitempty"`
	Protocol *PortProtocol `json:"protocol,omitempty"`
}

// PortProtocol defines model for Port.Protocol.
type PortProtocol string

// StorageSpec defines model for StorageSpec.
type StorageSpec struct {
	Size        *string `json:"size,omitempty"`
	SnapshotRef *struct {
		Name      *string `json:"name,omitempty"`
		Namespace *string `json:"namespace,omitempty"`
	} `json:"snapshotRef,omitempty"`
	StorageClass *string `json:"storageClass,omitempty"`
}

// Name defines model for Name.
type Name = string

// Namespace defines model for Namespace.
type Namespace = string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ExecuteActionJSONBody defines parameters for ExecuteAction.
type ExecuteActionJSONBody map[string]string

// CreateAPIKeyJSONRequestBody defines body for CreateAPIKey for application/json ContentType.
type CreateAPIKeyJSONRequestBody = CreateAPIKeyRequest

// CreateGameServerJSONRequestBody defines body for CreateGameServer for application/json ContentType.
type CreateGameServerJSONRequestBody = GameServer

// ExecuteActionJSONRequestBody defines body for ExecuteAction for application/json ContentType.
type ExecuteActionJSONRequestBody ExecuteActionJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List API keys
	// (GET /api/v1/apikeys)
	ListAPIKeys(w http.ResponseWriter, r *http.Request)
	// Create API key
	// (POST /api/v1/apikeys)
	CreateAPIKey(w http.ResponseWriter, r *http.Request)
	// Revoke API key
	// (DELETE /api/v1/apikeys/{keyId})
	DeleteAPIKey(w http.ResponseWriter, r *http.Request, keyId string)
	// List fleets
	// (GET /api/v1/gameserverfleets)
	ListGameServerFleets(w http.ResponseWriter, r *http.Request)
	// Get fleet
	// (GET /api/v1/gameserverfleets/{namespace}/{name})
	GetGameServerFleet(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name)
	// List game servers
	// (GET /api/v1/gameservers)
	ListGameServers(w http.ResponseWriter, r *http.Request)
	// Create game server
	// (POST /api/v1/gameservers/{namespace})
	CreateGameServer(w http.ResponseWriter, r *http.Request, namespace string)
	// Delete game server
	// (DELETE /api/v1/gameservers/{namespace}/{name})
	DeleteGameServer(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name)
	// Get game server
	// (GET /api/v1/gameservers/{namespace}/{name})
	GetGameServer(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name)
	// List available actions
	// (GET /api/v1/gameservers/{namespace}/{name}/actions)
	ListActions(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name)
	// Execute action
	// (POST /api/v1/gameservers/{namespace}/{name}/actions/{action})
	ExecuteAction(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name, action string)
	// Console WebSocket stream
	// (GET /api/v1/gameservers/{namespace}/{name}/console)
	GetConsole(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name)
	// Get action execution status
	// (GET /api/v1/gameservers/{namespace}/{name}/executions/{executionId})
	GetActionExecution(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name, executionId string)
	// List snapshots
	// (GET /api/v1/gameservers/{namespace}/{name}/snapshots)
	ListSnapshots(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name)
	// Create snapshot
	// (POST /api/v1/gameservers/{namespace}/{name}/snapshots)
	CreateSnapshot(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name)
	// List profiles
	// (GET /api/v1/profiles)
	ListProfiles(w http.ResponseWriter, r *http.Request)
	// Get profile
	// (GET /api/v1/profiles/{name})
	GetProfile(w http.ResponseWriter, r *http.Request, name string)
	// Auth configuration discovery
	// (GET /auth/config)
	GetAuthConfig(w http.ResponseWriter, r *http.Request)
	// Liveness probe
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// Readiness probe
	// (GET /readyz)
	GetReadyz(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List API keys
// (GET /api/v1/apikeys)
func (_ Unimplemented) ListAPIKeys(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create API key
// (POST /api/v1/apikeys)
func (_ Unimplemented) CreateAPIKey(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Revoke API key
// (DELETE /api/v1/apikeys/{keyId})
func (_ Unimplemented) DeleteAPIKey(w http.ResponseWriter, r *http.Request, keyId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List fleets
// (GET /api/v1/gameserverfleets)
func (_ Unimplemented) ListGameServerFleets(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get fleet
// (GET /api/v1/gameserverfleets/{namespace}/{name})
func (_ Unimplemented) GetGameServerFleet(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List game servers
// (GET /api/v1/gameservers)
func (_ Unimplemented) ListGameServers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create game server
// (POST /api/v1/gameservers/{namespace})
func (_ Unimplemented) CreateGameServer(w http.ResponseWriter, r *http.Request, namespace string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete game server
// (DELETE /api/v1/gameservers/{namespace}/{name})
func (_ Unimplemented) DeleteGameServer(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get game server
// (GET /api/v1/gameservers/{namespace}/{name})
func (_ Unimplemented) GetGameServer(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List available actions
// (GET /api/v1/gameservers/{namespace}/{name}/actions)
func (_ Unimplemented) ListActions(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Execute action
// (POST /api/v1/gameservers/{namespace}/{name}/actions/{action})
func (_ Unimplemented) ExecuteAction(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name, action string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Console WebSocket stream
// (GET /api/v1/gameservers/{namespace}/{name}/console)
func (_ Unimplemented) GetConsole(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get action execution status
// (GET /api/v1/gameservers/{namespace}/{name}/executions/{executionId})
func (_ Unimplemented) GetActionExecution(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name, executionId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List snapshots
// (GET /api/v1/gameservers/{namespace}/{name}/snapshots)
func (_ Unimplemented) ListSnapshots(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create snapshot
// (POST /api/v1/gameservers/{namespace}/{name}/snapshots)
func (_ Unimplemented) CreateSnapshot(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List profiles
// (GET /api/v1/profiles)
func (_ Unimplemented) ListProfiles(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get profile
// (GET /api/v1/profiles/{name})
func (_ Unimplemented) GetProfile(w http.ResponseWriter, r *http.Request, name string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Auth configuration discovery
// (GET /auth/config)
func (_ Unimplemented) GetAuthConfig(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Liveness probe
// (GET /healthz)
func (_ Unimplemented) GetHealthz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Readiness probe
// (GET /readyz)
func (_ Unimplemented) GetReadyz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListAPIKeys operation middleware
func (siw *ServerInterfaceWrapper) ListAPIKeys(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAPIKeys(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAPIKey operation middleware
func (siw *ServerInterfaceWrapper) CreateAPIKey(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAPIKey(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAPIKey operation middleware
func (siw *ServerInterfaceWrapper) DeleteAPIKey(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "keyId" -------------
	var keyId string

	err = runtime.BindStyledParameterWithOptions("simple", "keyId", chi.URLParam(r, "keyId"), &keyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "keyId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAPIKey(w, r, keyId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListGameServerFleets operation middleware
func (siw *ServerInterfaceWrapper) ListGameServerFleets(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListGameServerFleets(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGameServerFleet operation middleware
func (siw *ServerInterfaceWrapper) GetGameServerFleet(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace Namespace

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", chi.URLParam(r, "namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name Name

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGameServerFleet(w, r, namespace, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListGameServers operation middleware
func (siw *ServerInterfaceWrapper) ListGameServers(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListGameServers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateGameServer operation middleware
func (siw *ServerInterfaceWrapper) CreateGameServer(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", chi.URLParam(r, "namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateGameServer(w, r, namespace)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteGameServer operation middleware
func (siw *ServerInterfaceWrapper) DeleteGameServer(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace Namespace

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", chi.URLParam(r, "namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name Name

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteGameServer(w, r, namespace, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGameServer operation middleware
func (siw *ServerInterfaceWrapper) GetGameServer(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace Namespace

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", chi.URLParam(r, "namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name Name

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGameServer(w, r, namespace, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListActions operation middleware
func (siw *ServerInterfaceWrapper) ListActions(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace Namespace

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", chi.URLParam(r, "namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name Name

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListActions(w, r, namespace, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExecuteAction operation middleware
func (siw *ServerInterfaceWrapper) ExecuteAction(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace Namespace

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", chi.URLParam(r, "namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name Name

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// ------------- Path parameter "action" -------------
	var action string

	err = runtime.BindStyledParameterWithOptions("simple", "action", chi.URLParam(r, "action"), &action, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "action", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExecuteAction(w, r, namespace, name, action)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetConsole operation middleware
func (siw *ServerInterfaceWrapper) GetConsole(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace Namespace

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", chi.URLParam(r, "namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name Name

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetConsole(w, r, namespace, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetActionExecution operation middleware
func (siw *ServerInterfaceWrapper) GetActionExecution(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace Namespace

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", chi.URLParam(r, "namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name Name

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// ------------- Path parameter "executionId" -------------
	var executionId string

	err = runtime.BindStyledParameterWithOptions("simple", "executionId", chi.URLParam(r, "executionId"), &executionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "executionId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetActionExecution(w, r, namespace, name, executionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSnapshots operation middleware
func (siw *ServerInterfaceWrapper) ListSnapshots(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace Namespace

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", chi.URLParam(r, "namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name Name

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSnapshots(w, r, namespace, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSnapshot operation middleware
func (siw *ServerInterfaceWrapper) CreateSnapshot(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace Namespace

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", chi.URLParam(r, "namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name Name

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSnapshot(w, r, namespace, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProfiles operation middleware
func (siw *ServerInterfaceWrapper) ListProfiles(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProfiles(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProfile operation middleware
func (siw *ServerInterfaceWrapper) GetProfile(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProfile(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthConfig operation middleware
func (siw *ServerInterfaceWrapper) GetAuthConfig(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadyz operation middleware
func (siw *ServerInterfaceWrapper) GetReadyz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadyz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/apikeys", wrapper.ListAPIKeys)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/apikeys", wrapper.CreateAPIKey)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/apikeys/{keyId}", wrapper.DeleteAPIKey)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/gameserverfleets", wrapper.ListGameServerFleets)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/gameserverfleets/{namespace}/{name}", wrapper.GetGameServerFleet)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/gameservers", wrapper.ListGameServers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/gameservers/{namespace}", wrapper.CreateGameServer)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/gameservers/{namespace}/{name}", wrapper.DeleteGameServer)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/gameservers/{namespace}/{name}", wrapper.GetGameServer)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/gameservers/{namespace}/{name}/actions", wrapper.ListActions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/gameservers/{namespace}/{name}/actions/{action}", wrapper.ExecuteAction)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/gameservers/{namespace}/{name}/console", wrapper.GetConsole)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/gameservers/{namespace}/{name}/executions/{executionId}", wrapper.GetActionExecution)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/gameservers/{namespace}/{name}/snapshots", wrapper.ListSnapshots)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/gameservers/{namespace}/{name}/snapshots", wrapper.CreateSnapshot)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/profiles", wrapper.ListProfiles)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/profiles/{name}", wrapper.GetProfile)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/config", wrapper.GetAuthConfig)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealthz)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/readyz", wrapper.GetReadyz)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xc63LbOJZ+FSx3q8bppSWnu7d6yvPLcS7jSSdRWcn0VtmuFQQeiRiTAAcAZSsuVe1D",
	"7BPuk0zhwpsIUpStONPzy5IIHByc64eDQz8EhKcZZ8CUDE4fggwLnIICYb59xCnov5QFp0GGVRyEATO/",
	"2T9hIODvORUQBadK5BAGksSQYj1HrTM9TipB2TLYbEJDTWaY9JG0z/ehu9GDZcaZBMPzKxxdwt9zkEp/",
	"I5wpYOYjzrKEEqwoZ+O/Sc70bxXZ/xCwCE6Dfx9X8hjbp3L8Rggu7FIRSCJopokEp8EFW+GERki4BTdh",
	"8JaLOY0iYM+xuswXC0ooMIUyECmVknImNRsfuXrLcxZ9ey4uQfJcEECMK7Qwa27C4AvDuYq5oF/hGXg4",
	"y1UMTDmqqDQePdJN1rTPJhfvYW3MXPAMhKLWZIgArCA6M+wtuEixCk6DCCs4VtSY+ZbRhcWUV2uPSRYG",
	"7XkgeGIeAMvT4PQqWFG4AxGEgWYHK64/4iilLLgJPR7kfuHzvwEx1mZ3dG6ZOcjGbq2AmvL9HAM6m1yg",
	"W1ijFU5yQEcy5ncMcUbghY/MTgm0HtxhwfRHb+iowsFVGXk0IcvvjU8yxPLeEglnJBcCGHH7XOA80VLB",
	"ScLvgrBUjQRBcUK/6kXgniS5pCv92Y678ey5IbN9rMIEXcMdjiKq5+Nk0uC6zyvsTieaRuCzEa1pnhsT",
	"gHucZlr+wX+lwTADM8Tf3APJ/fLEGf0rCNm151tqY1C18jZFjyBTUDjCamc8+GTY/AAK61kyA+Lhzyz3",
	"sUv0BCcJiEdqpTWlLXsslqAu9RYeKbjhVsTq6XWnan3cSoVVLn0+o3W3ZyABE6y9IQCkcTnPI6mw2HMd",
	"zXQjpk6ARfpZGFzmjNlP05wQgAiiIAzeYpqYD5egNw7RoFg7wDm8ai7U1Qyo5Rx08drriK2A1x3jrOe3",
	"Fi4jm1cDBfXy4ZzzBDCrrLgSqJsXBixP5yZbFYMHJqlcxeecLeiyEQkeAg0RPvBI83sVzLGkRGdCGuk/",
	"OKMutJsHbxieJxUc1IMupMy16waxUpk8HY81udEvt0vB82xEeDoWgJNUjlPKsOLGpZseWC2/rZ+zFaaJ",
	"XhHhJrRIzfgwoApsbCiExDjT5tm5i65YgYXAa/29uc1thn6LQcUg0Cs9yjCFqETghoceLdZFtE3t08Xr",
	"c0TNQ/Tl8ld0RBfI/VbQ1Fm9dMBcUKP+xMikUEK/1VbS3dqbz5ItgrFopobeh7jSe1gjBwk6wcYWYuUJ",
	"oAUXSMVgIM2R8xWJFDc/2qzwB4k0gRc1ULAnXhvkxW9YlHHKPBvGUSRAyj3BBBd1p6dMwRKE3zPfsNVf",
	"sdgvduxCOQ5A7hVzvLwV+aPJWlda2ZK2HeYT9zucwkTwBbWm8UQ0U6d2cCTTN6O28FQP98pwe1AHOjIf",
	"y4i2G2v6whdegs+EaYqXfjtddcrZtxOCMzynCS3oNleZY3KbZ/5spjcv/Y8ESMUFvBU8nTKcyZgr/0C5",
	"UNlQu42ozBK87kScwFZUcJY6cQ0Su/NTj9hL+TZDnFY8kiBWIJA+emPKQCA72GOmfK7HWgF7zsdGtx9A",
	"CUo8wjdFnKdGIr0+JfCBM6q8bl8lxrZ6NGWxwsmjga/mdLgTTPS+PLoQrhLikVFCU6p8yDrLvaJLIeVi",
	"PdA3XPXp25D3nxO4cGbXXC/lOVOTLnuQ9Cu87swsWwG8InUziCdt8VNj8LuiehW8iyQ+sghxRPl49dJb",
	"FPHGfbfcs4d9u66N+vVD28B5dvwOIb5NANSB8mOd4jc+7WeCckHV+jzBUnaG4KxK/x6YYqqT0he4wkBB",
	"miXuvNlc+THK81YMeMYTvlxPMwE4OudMKoEp2wpP7WlbsSjP9KF5qgRWsPSEdMGThLLlFzPM48j4/gvD",
	"xSFoaBDfPjheNhbRB25bkHz0gburQFFyetmrPcKZLeTsKUytiXU/6X6zsdqI+khs9oxyfjwHbLVXwWqr",
	"KlFBE7TCgmqJysDDRkIXQNbEi6BzxacKiw4kRaMEPtuC5BS0PuRQ40o4jl7hBDMC4mLShjwTyhBG2g3p",
	"ghIE9woEwwm6mJRnvWWFiv4g0a81gsjhD1982jumbN+PLEAAI6APlzVA3nlorWXXvmAytcP6wX8j5Ptx",
	"XV88f6zDgDvSyj0QrjsEe6hpOA3iHGeYOHjalPAHfE/TPEV2HCLFwNDjiXaMp+Jzbi4FVElEww8vhXa9",
	"UfAV1SLcLjpeROZQOFU8y0yR5s3WobQP1Bnt1Q4lh8jDBblvnISXpeG5iqgnySpgXfczOVP+KBrlAqsW",
	"iPvlx5N42F2G3kOU+3z0XHCG4D4TYG5QTcAoRkdIOrnJgct0eJvJIntVtulX6KqSd5a89SJVkfuxibam",
	"Zv+lIuVMh3GpcJoN31GC55A88UrlQPcfYTBxx9PW/aA9LU86Tq9hAPcZl0WR1h1nbEXUX7NVMZVIHzGR",
	"/pvPEypjiBBnJimViao/H9VyKOvJQYoTnjQvNj+fT2oVTPvty+vJwDhUTzNt0OsstPLGH0/eUa8tOx/q",
	"vSN5skpd6jSZeujpVgLJdXqf6ghXRtf3sD7L7Tm2qdRfYYnJGuGEYmniRHEv3rwo+BPKhE78aHbm+iDM",
	"z6foFWABYhaEtgMmBhyZM6Trgfnv47PJxfF7qGUvy015ReBnq7oXqF1WHCWc4ARFsIKEZwbWcZasXwSu",
	"K8LYlbuwcIvFSmVmKcOmfy1zU/CX3z4jxW/BBss4TzGTIeICYWRP06Vgjmb2h/8ZjUazF3r4NUsxiSkr",
	"Cu1yhGblxmfaSzAhkCmIEJYIo6RD5nJ0zRp7MUxvb2ZjKkQLXno3UZXRBb+8R+8Ez7MgDHKR1G6TahdJ",
	"baR8+Wb62XChuUkxw0vKlnV8KUO00AdeGSKHDGWIMKslk9E1O0sSVEIllLNI28sYZ3S8ejkruli2lQr3",
	"WjToLgZhem4gGl2za/ZZB5mIk9yomUoTW374wfXm8AVSIlfxDz+UYFhzr8UhMFHX7EgCoFnEiRxjQWKq",
	"gKhcgGbmmHC2sulajtJo9mKEbHZHgucKJMIC0BIY6LNmdM0WgqeIqj8hiKgyS2mYgBZUSBXq7wwJKMZb",
	"DSqqTPT4YC3nXLPFEzRJMDOMBrVycfBydDI6MVXLDBjOaHAa/DQ6Gf0UhKYUaTzYCXFs798sKrH1jC1v",
	"plIhnCSlRaE7qmKeKyT1WVXZbheJjswlT+k9tnBEObuIHBF7dSWDrWa0H09O9up+GlaEt21MLaTc7osy",
	"2+OLcnd6zs8nL7sWKFkfN9q3zKSfdk+qWt9MXM3TFIt1wUXJQhgovDQ3vvonI7QbU4KVHv28c2aCMGJw",
	"V4WUPnXU7xKDsjr6ikfrgzWi+a4rN80KpgYEm5Y1vDwYC83OL19PnJOV6wFDR1XzVr13yyj3ZLdya22V",
	"38WI7E4LC/Bb0Sbcdvzxwy2sL6KNtawElAf8vza/jwWs+C0gzIZZmZ1VWlm9b/bK291qGNmrs/WmZT4/",
	"ezoVHLOW/ejZlKNn/Lx7RtmH2tTmpRX2UG3qxGrzqk2qu+P5Vt1ZIwrBpTTPSlQpvaF8e+qzxPTtOvke",
	"wd2J5HGKbwfqRbHpQiVOCr0KGT+UQt3Yz5tOHb0DVS/UtW8Imip5B6o9ZMvdfDuuhoyrxvNNOGhw4PG9",
	"k4OF7pau27o1D1AECtNEPtXZtMAXxe3LIKXu5WCP863ndqt9PKqO4w/mVw2ilSLqEunSRt27zOnZi5Vc",
	"hrRIqSKLKCtBOF1QiCodDcFRjYvO3Vnuce9w3HwbmFbX/vOis+2Ve7ozCgT3+8JhNWt+gjHXUkU/OkO4",
	"btEDgFmf2T5Htvi5vyfH7vb3gtacDoboPNwz56P5uhaPMIuKa7EeEPCvk/93BYcDAoCDOuy41jfYAxPs",
	"IFTezpvaE66zguZY2lI4VbKolPkLLG7F34Hun9RJ2Y1KKjEW0n+iWVgltajWDmPul0dYxvjBfujBK/Yd",
	"CHPitmO1GTSt46jo0PrPjmDvaDhhPoNthF7Ug4v1nwXyDL47q71qkYKUpqkg+DMkCXfX3PLfPFds7Vdq",
	"D1q3ar8z4yteEVfrLl6TcS8GfR/MU1pqoeanOAjhTLrXEryh80u2FDgC8y4CRr/BfMrJLShEOGNAnDAE",
	"4JSyJUroCpCjiHiuslzpJHrN7AWKHlI8JTxNMYvkCH2OATl7QMWVIaISRbCgDCJE2TVzVwFLYOrY3R/p",
	"/Thix8W0URrN0JE2oAj9ZfrpI1pof5Gn14wk5rVkCSySaCYIZ7PxLKNsOQsL73bPEr6cjc2I40IVs/HM",
	"3qLPxjPTyT97Mbpml9a5JCqignk9A3GBYrqMQdi7hBZwOHcC/w6Z46U11aaCp3dUkVirZuKkKNH//+//",
	"1VRt9YtAKuwui/+ZjwdPS0JOO63d17ysUOA+XlZGDjl+KD+7QnAnQjXHZGN3Jt+WeQlqL6u2zKv9Put3",
	"SkK1bT6xzHzyraL9oFB/QNCLPWlE5U+FOFU/UC/8LYe1Ya8X4U5rbUb/Ghi30XS2B9KtBOwBrI1uLKfF",
	"SnTdV4lleawg4DmN7MSblkitke47KOrAVapSP219FM+aRarvVHGSte5Fj9pr7ls0XAwrYrt2XImOSJJL",
	"BeJYEp7ZF2DbTlqMfrbqdfFy4b7l61IIh6pfZ9XOC/mXwvCK/xH3QJOOAsA7UNWjYUXof5oU2FBiW2lF",
	"N/gBs15VRulSVK5iDeXdG/le7VyCygWzbUS49214U7Wz1FyD7si1IxW9TWXfIzFjcwkRmq8N6S8X5pyT",
	"K35ckLCrdID52v8S+JawpVql478NNTfcaCQMTq9u6ippD0cRlYSvQDRuvnMVO/3EgBMVf92pmx9PTtCn",
	"94gu7EvrrmsqM11TVCJRdqK3xPhnt8JOGSq4V+MswXRLerWX6G49bdEtmZ1vM4f10bVXbr/SFTCQpiw4",
	"r1uzZd7JynRVP11Umoq2RAMEUPlGpUd0l3bB7yc5w2uv5DSLdIfomtMfGg2fVzcantS6Te0P9bbYqxsd",
	"NMvb4qtWit3uPG30V56Ox6Y1NeZSnf7x5I8nBuc4Jlsv9tjIYZ0CkRjIraxivduR5q/3f4LVXc5NNTtp",
	"T6wX4MsXnWyTJ7idOAL16nk/Hc9BsmCirOX2zS8xq4+NCgb1EzE9AF4Kb4sWEu90l0+8MycVzGijrFpt",
	"qixZVVOLY71Hda6nybdg2SC0udn8IwAA//+BZHgNvVAAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
