// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

const (
	ApiKeyAuthScopes = "apiKeyAuth.Scopes"
	BasicAuthScopes  = "basicAuth.Scopes"
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for APIKeyRole.
const (
	APIKeyRoleAdmin    APIKeyRole = "admin"
	APIKeyRoleOperator APIKeyRole = "operator"
	APIKeyRoleViewer   APIKeyRole = "viewer"
)

// Defines values for ActionConcurrency.
const (
	Allow     ActionConcurrency = "allow"
	Exclusive ActionConcurrency = "exclusive"
	Serialize ActionConcurrency = "serialize"
)

// Defines values for ActionExecutionStatusState.
const (
	ActionExecutionStatusStateFailed    ActionExecutionStatusState = "Failed"
	ActionExecutionStatusStatePending   ActionExecutionStatusState = "Pending"
	ActionExecutionStatusStateRejected  ActionExecutionStatusState = "Rejected"
	ActionExecutionStatusStateRunning   ActionExecutionStatusState = "Running"
	ActionExecutionStatusStateSucceeded ActionExecutionStatusState = "Succeeded"
)

// Defines values for ActionParamType.
const (
	Boolean ActionParamType = "boolean"
	Number  ActionParamType = "number"
	String  ActionParamType = "string"
)

// Defines values for AuthConfigAuthModes.
const (
	Apikey AuthConfigAuthModes = "apikey"
	Basic  AuthConfigAuthModes = "basic"
	None   AuthConfigAuthModes = "none"
	Oidc   AuthConfigAuthModes = "oidc"
)

// Defines values for CreateAPIKeyRequestRole.
const (
	CreateAPIKeyRequestRoleAdmin    CreateAPIKeyRequestRole = "admin"
	CreateAPIKeyRequestRoleOperator CreateAPIKeyRequestRole = "operator"
	CreateAPIKeyRequestRoleViewer   CreateAPIKeyRequestRole = "viewer"
)

// Defines values for GameServerFleetSpecUpdateStrategyType.
const (
	Recreate      GameServerFleetSpecUpdateStrategyType = "Recreate"
	RollingUpdate GameServerFleetSpecUpdateStrategyType = "RollingUpdate"
)

// Defines values for GameServerStatusState.
const (
	GameServerStatusStateError        GameServerStatusState = "Error"
	GameServerStatusStateIdle         GameServerStatusState = "Idle"
	GameServerStatusStateProvisioning GameServerStatusState = "Provisioning"
	GameServerStatusStateRunning      GameServerStatusState = "Running"
	GameServerStatusStateStopped      GameServerStatusState = "Stopped"
)

// Defines values for GameSnapshotStatusState.
const (
	Failed  GameSnapshotStatusState = "Failed"
	Pending GameSnapshotStatusState = "Pending"
	Ready   GameSnapshotStatusState = "Ready"
)

// Defines values for PortProtocol.
const (
	TCP PortProtocol = "TCP"
	UDP PortProtocol = "UDP"
)

// APIKey defines model for APIKey.
type APIKey struct {
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	CreatedBy *string    `json:"createdBy,omitempty"`

	// ExpiresAt Optional expiry time; expired keys are rejected with 401
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
	Name      *string    `json:"name,omitempty"`

	// Namespaces Namespace patterns the key is restricted to (empty = cluster-wide)
	Namespaces *[]string   `json:"namespaces,omitempty"`
	Role       *APIKeyRole `json:"role,omitempty"`
}

// APIKeyRole defines model for APIKey.Role.
type APIKeyRole string

// APIKeyCreated defines model for APIKeyCreated.
type APIKeyCreated struct {
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`

	// Key The API key value (shown once)
	Key        string    `json:"key"`
	Name       string    `json:"name"`
	Namespaces *[]string `json:"namespaces,omitempty"`
	Role       string    `json:"role"`
	Warning    *string   `json:"warning,omitempty"`
}

// Action defines model for Action.
type Action struct {
	Concurrency *ActionConcurrency      `json:"concurrency,omitempty"`
	Description *string                 `json:"description,omitempty"`
	Name        *string                 `json:"name,omitempty"`
	Params      *map[string]ActionParam `json:"params,omitempty"`
	Timeout     *string                 `json:"timeout,omitempty"`
}

// ActionConcurrency defines model for Action.Concurrency.
type ActionConcurrency string

// ActionExecution defines model for ActionExecution.
type ActionExecution struct {
	ApiVersion *string     `json:"apiVersion,omitempty"`
	Kind       *string     `json:"kind,omitempty"`
	Metadata   *ObjectMeta `json:"metadata,omitempty"`
	Spec       *struct {
		ActionName *string            `json:"actionName,omitempty"`
		Caller     *string            `json:"caller,omitempty"`
		Params     *map[string]string `json:"params,omitempty"`
		TargetRef  *struct {
			ApiVersion *string `json:"apiVersion,omitempty"`
			Kind       *string `json:"kind,omitempty"`
			Name       *string `json:"name,omitempty"`
			Namespace  *string `json:"namespace,omitempty"`
		} `json:"targetRef,omitempty"`
	} `json:"spec,omitempty"`
	Status *struct {
		CompletedAt *time.Time                  `json:"completedAt,omitempty"`
		Error       *string                     `json:"error,omitempty"`
		Result      *string                     `json:"result,omitempty"`
		StartedAt   *time.Time                  `json:"startedAt,omitempty"`
		State       *ActionExecutionStatusState `json:"state,omitempty"`
	} `json:"status,omitempty"`
}

// ActionExecutionStatusState defines model for ActionExecution.Status.State.
type ActionExecutionStatusState string

// ActionExecutionRef defines model for ActionExecutionRef.
type ActionExecutionRef struct {
	// Name Execution ID
	Name string `json:"name"`
}

// ActionParam defines model for ActionParam.
type ActionParam struct {
	Default  *string          `json:"default,omitempty"`
	Required *bool            `json:"required,omitempty"`
	Type     *ActionParamType `json:"type,omitempty"`
}

// ActionParamType defines model for ActionParam.Type.
type ActionParamType string

// AuthConfig defines model for AuthConfig.
type AuthConfig struct {
	// AuthModes Available authentication modes
	AuthModes []AuthConfigAuthModes `json:"authModes"`

	// BasicEnabled Whether Basic auth is enabled
	BasicEnabled bool `json:"basicEnabled"`

	// OidcIssuer OIDC issuer URL (if OIDC is enabled)
	OidcIssuer *string `json:"oidcIssuer"`
}

// AuthConfigAuthModes defines model for AuthConfig.AuthModes.
type AuthConfigAuthModes string

// CreateAPIKeyRequest defines model for CreateAPIKeyRequest.
type CreateAPIKeyRequest struct {
	// ExpiresAt Optional expiry time (must be in the future)
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`

	// Name Key name
	Name string `json:"name"`

	// Namespaces Optional namespace patterns (exact names or trailing-"*" globs such as "tenant-*") restricting the key. Omit for a cluster-wide key.
	Namespaces *[]string `json:"namespaces,omitempty"`

	// Role Role for the key (defaults to the caller's role)
	Role *CreateAPIKeyRequestRole `json:"role,omitempty"`
}

// CreateAPIKeyRequestRole Role for the key (defaults to the caller's role)
type CreateAPIKeyRequestRole string

// Endpoint defines model for Endpoint.
type Endpoint struct {
	Address *string `json:"address,omitempty"`
	Name    *string `json:"name,omitempty"`
	Port    *int    `json:"port,omitempty"`
}

// EnvVar defines model for EnvVar.
type EnvVar struct {
	Default     *string `json:"default,omitempty"`
	Description *string `json:"description,omitempty"`
	Key         *string `json:"key,omitempty"`
	Required    *bool   `json:"required,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// GameProfile defines model for GameProfile.
type GameProfile struct {
	ApiVersion *string          `json:"apiVersion,omitempty"`
	Kind       *string          `json:"kind,omitempty"`
	Metadata   *ObjectMeta      `json:"metadata,omitempty"`
	Spec       *GameProfileSpec `json:"spec,omitempty"`
}

// GameProfileSpec defines model for GameProfileSpec.
type GameProfileSpec struct {
	Actions *[]Action `json:"actions,omitempty"`
	Agent   *struct {
		Image   *string `json:"image,omitempty"`
		Version *string `json:"version,omitempty"`
	} `json:"agent,omitempty"`
	Capabilities *struct {
		Backup              *bool `json:"backup,omitempty"`
		Files               *bool `json:"files,omitempty"`
		RestoreFromSnapshot *bool `json:"restoreFromSnapshot,omitempty"`
		Sftp                *bool `json:"sftp,omitempty"`
	} `json:"capabilities,omitempty"`

	// Category Storefront category (e.g. sandbox, fps, survival, mmo)
	Category *string `json:"category,omitempty"`

	// Description Markdown blurb describing the game for storefronts
	Description *string   `json:"description,omitempty"`
	DisplayName *string   `json:"displayName,omitempty"`
	Environment *[]EnvVar `json:"environment,omitempty"`

	// Icon URL to an icon image for storefront display
	Icon *string `json:"icon,omitempty"`

	// Image Game server container image
	Image         *string `json:"image,omitempty"`
	Observability *struct {
		AgentMetrics *struct {
			Path *string `json:"path,omitempty"`
			Port *int    `json:"port,omitempty"`
		} `json:"agentMetrics,omitempty"`
		ServiceMonitor *struct {
			Enabled  *bool   `json:"enabled,omitempty"`
			Interval *string `json:"interval,omitempty"`
		} `json:"serviceMonitor,omitempty"`
	} `json:"observability,omitempty"`
	Ports     *[]Port `json:"ports,omitempty"`
	Resources *struct {
		// Default Name of the tier applied when a GameServer does not specify one
		Default *string `json:"default,omitempty"`
		Limits  *struct {
			Cpu    *string `json:"cpu,omitempty"`
			Memory *string `json:"memory,omitempty"`
		} `json:"limits,omitempty"`
		Requests *struct {
			Cpu    *string `json:"cpu,omitempty"`
			Memory *string `json:"memory,omitempty"`
		} `json:"requests,omitempty"`

		// Tiers Named resource presets selectable via GameServer spec.tier
		Tiers *map[string]ResourceRequirements `json:"tiers,omitempty"`
	} `json:"resources,omitempty"`
	Storage *struct {
		MountPath   string  `json:"mountPath"`
		SizeDefault *string `json:"sizeDefault,omitempty"`
	} `json:"storage,omitempty"`
}

// GameServer defines model for GameServer.
type GameServer struct {
	ApiVersion *string           `json:"apiVersion,omitempty"`
	Kind       *string           `json:"kind,omitempty"`
	Metadata   *ObjectMeta       `json:"metadata,omitempty"`
	Spec       *GameServerSpec   `json:"spec,omitempty"`
	Status     *GameServerStatus `json:"status,omitempty"`
}

// GameServerFleet defines model for GameServerFleet.
type GameServerFleet struct {
	ApiVersion *string     `json:"apiVersion,omitempty"`
	Kind       *string     `json:"kind,omitempty"`
	Metadata   *ObjectMeta `json:"metadata,omitempty"`
	Spec       *struct {
		PriorityClassName *string `json:"priorityClassName,omitempty"`
		Profile           *string `json:"profile,omitempty"`
		Replicas          *int    `json:"replicas,omitempty"`
		Template          *struct {
			Spec *GameServerSpec `json:"spec,omitempty"`
		} `json:"template,omitempty"`
		TopologySpreadConstraints *[]map[string]interface{} `json:"topologySpreadConstraints,omitempty"`
		UpdateStrategy            *struct {
			RollingUpdate *struct {
				MaxUnavailable *int `json:"maxUnavailable,omitempty"`
			} `json:"rollingUpdate,omitempty"`
			Type *GameServerFleetSpecUpdateStrategyType `json:"type,omitempty"`
		} `json:"updateStrategy,omitempty"`
	} `json:"spec,omitempty"`
	Status *struct {
		AvailableReplicas *int                      `json:"availableReplicas,omitempty"`
		Conditions        *[]map[string]interface{} `json:"conditions,omitempty"`
		ReadyReplicas     *int                      `json:"readyReplicas,omitempty"`
		Replicas          *int                      `json:"replicas,omitempty"`
		UpdatedReplicas   *int                      `json:"updatedReplicas,omitempty"`
	} `json:"status,omitempty"`
}

// GameServerFleetSpecUpdateStrategyType defines model for GameServerFleet.Spec.UpdateStrategy.Type.
type GameServerFleetSpecUpdateStrategyType string

// GameServerFleetPatch Strict merge-patch for fleet scaling. Only spec.replicas is accepted; unknown fields are rejected with 400.
type GameServerFleetPatch struct {
	Spec *struct {
		Replicas *int `json:"replicas,omitempty"`
	} `json:"spec,omitempty"`
}

// GameServerLifecycle defines model for GameServerLifecycle.
type GameServerLifecycle struct {
	// AutoStart Whether the server should be running. false gracefully stops a running server (agent PrepareShutdown, scale to 0, state Stopped); true starts a stopped server again.
	AutoStart *bool `json:"autoStart,omitempty"`

	// IdleTimeoutSeconds Seconds of player-idle time before auto-shutdown (0 = never)
	IdleTimeoutSeconds *int `json:"idleTimeoutSeconds,omitempty"`
}

// GameServerLifecyclePatch Strict merge-patch for GameServer lifecycle control. Only spec.lifecycle.autoStart / spec.lifecycle.idleTimeoutSeconds are accepted; unknown fields are rejected with 400.
type GameServerLifecyclePatch struct {
	Spec *struct {
		Lifecycle *GameServerLifecycle `json:"lifecycle,omitempty"`
	} `json:"spec,omitempty"`
}

// GameServerSpec defines model for GameServerSpec.
type GameServerSpec struct {
	// Env Environment variables
	Env       *map[string]string `json:"env,omitempty"`
	Lifecycle *struct {
		AutoStart          *bool `json:"autoStart,omitempty"`
		IdleTimeoutSeconds *int  `json:"idleTimeoutSeconds,omitempty"`
	} `json:"lifecycle,omitempty"`

	// LoadBalancerIP Pin a specific external IP for the game server's LoadBalancer service
	LoadBalancerIP    *string `json:"loadBalancerIP,omitempty"`
	PriorityClassName *string `json:"priorityClassName,omitempty"`

	// Profile Reference to GameProfile name
	Profile *string      `json:"profile,omitempty"`
	Storage *StorageSpec `json:"storage,omitempty"`

	// Tier Resource tier from the GameProfile's spec.resources.tiers
	Tier *string `json:"tier,omitempty"`
}

// GameServerStatus defines model for GameServerStatus.
type GameServerStatus struct {
	AgentVersion *string                   `json:"agentVersion,omitempty"`
	Conditions   *[]map[string]interface{} `json:"conditions,omitempty"`
	Endpoints    *[]Endpoint               `json:"endpoints,omitempty"`

	// PlayerCapacity Maximum player capacity
	PlayerCapacity *int `json:"playerCapacity,omitempty"`

	// Players Current player count
	Players *int                   `json:"players,omitempty"`
	State   *GameServerStatusState `json:"state,omitempty"`
}

// GameServerStatusState defines model for GameServerStatus.State.
type GameServerStatusState string

// GameSnapshot defines model for GameSnapshot.
type GameSnapshot struct {
	ApiVersion *string     `json:"apiVersion,omitempty"`
	Kind       *string     `json:"kind,omitempty"`
	Metadata   *ObjectMeta `json:"metadata,omitempty"`
	Spec       *struct {
		GameServerRef *string `json:"gameServerRef,omitempty"`
		Retention     *struct {
			Count    *int    `json:"count,omitempty"`
			Duration *string `json:"duration,omitempty"`
		} `json:"retention,omitempty"`

		// Schedule Cron expression for scheduled snapshots
		Schedule *string `json:"schedule,omitempty"`
	} `json:"spec,omitempty"`
	Status *struct {
		ReadyAt *time.Time               `json:"readyAt,omitempty"`
		Size    *string                  `json:"size,omitempty"`
		State   *GameSnapshotStatusState `json:"state,omitempty"`
	} `json:"status,omitempty"`
}

// GameSnapshotStatusState defines model for GameSnapshot.Status.State.
type GameSnapshotStatusState string

// ObjectMeta defines model for ObjectMeta.
type ObjectMeta struct {
	CreationTimestamp *time.Time         `json:"creationTimestamp,omitempty"`
	Labels            *map[string]string `json:"labels,omitempty"`
	Name              *string            `json:"name,omitempty"`
	Namespace         *string            `json:"namespace,omitempty"`
}

// Port defines model for Port.
type Port struct {
	ContainerPort *int `json:"containerPort,omitempty"`

	// Exposed Whether this port is published on the external LoadBalancer service
	Exposed  *bool         `json:"exposed,omitempty"`
	Name     *string       `json:"name,omitempty"`
	Protocol *PortProtocol `json:"protocol,omitempty"`
}

// PortProtocol defines model for Port.Protocol.
type PortProtocol string

// ResourceRequirements defines model for ResourceRequirements.
type ResourceRequirements struct {
	Limits *struct {
		Cpu    *string `json:"cpu,omitempty"`
		Memory *string `json:"memory,omitempty"`
	} `json:"limits,omitempty"`
	Requests *struct {
		Cpu    *string `json:"cpu,omitempty"`
		Memory *string `json:"memory,omitempty"`
	} `json:"requests,omitempty"`
}

// SFTPInfo defines model for SFTPInfo.
type SFTPInfo struct {
	// Host External hostname or IP of the game server
	Host     string `json:"host"`
	Password string `json:"password"`

	// Port SFTP port on the player-facing LoadBalancer service
	Port     int    `json:"port"`
	Username string `json:"username"`
}

// StorageSpec defines model for StorageSpec.
type StorageSpec struct {
	Size        *string `json:"size,omitempty"`
	SnapshotRef *struct {
		Name      *string `json:"name,omitempty"`
		Namespace *string `json:"namespace,omitempty"`
	} `json:"snapshotRef,omitempty"`
	StorageClass *string `json:"storageClass,omitempty"`
}

// Name defines model for Name.
type Name = string

// Namespace defines model for Namespace.
type Namespace = string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ExecuteActionJSONBody defines parameters for ExecuteAction.
type ExecuteActionJSONBody map[string]string

// CreateAPIKeyJSONRequestBody defines body for CreateAPIKey for application/json ContentType.
type CreateAPIKeyJSONRequestBody = CreateAPIKeyRequest

// CreateGameServerFleetJSONRequestBody defines body for CreateGameServerFleet for application/json ContentType.
type CreateGameServerFleetJSONRequestBody = GameServerFleet

// UpdateGameServerFleetJSONRequestBody defines body for UpdateGameServerFleet for application/json ContentType.
type UpdateGameServerFleetJSONRequestBody = GameServerFleetPatch

// CreateGameServerJSONRequestBody defines body for CreateGameServer for application/json ContentType.
type CreateGameServerJSONRequestBody = GameServer

// UpdateGameServerLifecycleJSONRequestBody defines body for UpdateGameServerLifecycle for application/json ContentType.
type UpdateGameServerLifecycleJSONRequestBody = GameServerLifecyclePatch

// ExecuteActionJSONRequestBody defines body for ExecuteAction for application/json ContentType.
type ExecuteActionJSONRequestBody ExecuteActionJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List API keys
	// (GET /api/v1/apikeys)
	ListAPIKeys(w http.ResponseWriter, r *http.Request)
	// Create API key
	// (POST /api/v1/apikeys)
	CreateAPIKey(w http.ResponseWriter, r *http.Request)
	// Revoke API key
	// (DELETE /api/v1/apikeys/{keyId})
	DeleteAPIKey(w http.ResponseWriter, r *http.Request, keyId string)
	// List fleets
	// (GET /api/v1/gameserverfleets)
	ListGameServerFleets(w http.ResponseWriter, r *http.Request)
	// Create fleet
	// (POST /api/v1/gameserverfleets/{namespace})
	CreateGameServerFleet(w http.ResponseWriter, r *http.Request, namespace string)
	// Delete fleet
	// (DELETE /api/v1/gameserverfleets/{namespace}/{name})
	DeleteGameServerFleet(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name)
	// Get fleet
	// (GET /api/v1/gameserverfleets/{namespace}/{name})
	GetGameServerFleet(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name)
	// Scale fleet
	// (PATCH /api/v1/gameserverfleets/{namespace}/{name})
	UpdateGameServerFleet(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name)
	// List game servers
	// (GET /api/v1/gameservers)
	ListGameServers(w http.ResponseWriter, r *http.Request)
	// Create game server
	// (POST /api/v1/gameservers/{namespace})
	CreateGameServer(w http.ResponseWriter, r *http.Request, namespace string)
	// Delete game server
	// (DELETE /api/v1/gameservers/{namespace}/{name})
	DeleteGameServer(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name)
	// Get game server
	// (GET /api/v1/gameservers/{namespace}/{name})
	GetGameServer(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name)
	// Patch game server lifecycle
	// (PATCH /api/v1/gameservers/{namespace}/{name})
	UpdateGameServerLifecycle(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name)
	// List available actions
	// (GET /api/v1/gameservers/{namespace}/{name}/actions)
	ListActions(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name)
	// Execute action
	// (POST /api/v1/gameservers/{namespace}/{name}/actions/{action})
	ExecuteAction(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name, action string)
	// Console WebSocket stream
	// (GET /api/v1/gameservers/{namespace}/{name}/console)
	GetConsole(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name)
	// Get action execution status
	// (GET /api/v1/gameservers/{namespace}/{name}/executions/{executionId})
	GetActionExecution(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name, executionId string)
	// Get SFTP connection info
	// (GET /api/v1/gameservers/{namespace}/{name}/sftp)
	GetSFTPInfo(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name)
	// List snapshots
	// (GET /api/v1/gameservers/{namespace}/{name}/snapshots)
	ListSnapshots(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name)
	// Create snapshot
	// (POST /api/v1/gameservers/{namespace}/{name}/snapshots)
	CreateSnapshot(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name)
	// List profiles
	// (GET /api/v1/profiles)
	ListProfiles(w http.ResponseWriter, r *http.Request)
	// Get profile
	// (GET /api/v1/profiles/{name})
	GetProfile(w http.ResponseWriter, r *http.Request, name string)
	// Auth configuration discovery
	// (GET /auth/config)
	GetAuthConfig(w http.ResponseWriter, r *http.Request)
	// Liveness probe
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// Readiness probe
	// (GET /readyz)
	GetReadyz(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List API keys
// (GET /api/v1/apikeys)
func (_ Unimplemented) ListAPIKeys(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create API key
// (POST /api/v1/apikeys)
func (_ Unimplemented) CreateAPIKey(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Revoke API key
// (DELETE /api/v1/apikeys/{keyId})
func (_ Unimplemented) DeleteAPIKey(w http.ResponseWriter, r *http.Request, keyId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List fleets
// (GET /api/v1/gameserverfleets)
func (_ Unimplemented) ListGameServerFleets(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create fleet
// (POST /api/v1/gameserverfleets/{namespace})
func (_ Unimplemented) CreateGameServerFleet(w http.ResponseWriter, r *http.Request, namespace string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete fleet
// (DELETE /api/v1/gameserverfleets/{namespace}/{name})
func (_ Unimplemented) DeleteGameServerFleet(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get fleet
// (GET /api/v1/gameserverfleets/{namespace}/{name})
func (_ Unimplemented) GetGameServerFleet(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Scale fleet
// (PATCH /api/v1/gameserverfleets/{namespace}/{name})
func (_ Unimplemented) UpdateGameServerFleet(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List game servers
// (GET /api/v1/gameservers)
func (_ Unimplemented) ListGameServers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create game server
// (POST /api/v1/gameservers/{namespace})
func (_ Unimplemented) CreateGameServer(w http.ResponseWriter, r *http.Request, namespace string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete game server
// (DELETE /api/v1/gameservers/{namespace}/{name})
func (_ Unimplemented) DeleteGameServer(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get game server
// (GET /api/v1/gameservers/{namespace}/{name})
func (_ Unimplemented) GetGameServer(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Patch game server lifecycle
// (PATCH /api/v1/gameservers/{namespace}/{name})
func (_ Unimplemented) UpdateGameServerLifecycle(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List available actions
// (GET /api/v1/gameservers/{namespace}/{name}/actions)
func (_ Unimplemented) ListActions(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Execute action
// (POST /api/v1/gameservers/{namespace}/{name}/actions/{action})
func (_ Unimplemented) ExecuteAction(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name, action string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Console WebSocket stream
// (GET /api/v1/gameservers/{namespace}/{name}/console)
func (_ Unimplemented) GetConsole(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get action execution status
// (GET /api/v1/gameservers/{namespace}/{name}/executions/{executionId})
func (_ Unimplemented) GetActionExecution(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name, executionId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get SFTP connection info
// (GET /api/v1/gameservers/{namespace}/{name}/sftp)
func (_ Unimplemented) GetSFTPInfo(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List snapshots
// (GET /api/v1/gameservers/{namespace}/{name}/snapshots)
func (_ Unimplemented) ListSnapshots(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create snapshot
// (POST /api/v1/gameservers/{namespace}/{name}/snapshots)
func (_ Unimplemented) CreateSnapshot(w http.ResponseWriter, r *http.Request, namespace Namespace, name Name) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List profiles
// (GET /api/v1/profiles)
func (_ Unimplemented) ListProfiles(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get profile
// (GET /api/v1/profiles/{name})
func (_ Unimplemented) GetProfile(w http.ResponseWriter, r *http.Request, name string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Auth configuration discovery
// (GET /auth/config)
func (_ Unimplemented) GetAuthConfig(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Liveness probe
// (GET /healthz)
func (_ Unimplemented) GetHealthz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Readiness probe
// (GET /readyz)
func (_ Unimplemented) GetReadyz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListAPIKeys operation middleware
func (siw *ServerInterfaceWrapper) ListAPIKeys(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAPIKeys(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAPIKey operation middleware
func (siw *ServerInterfaceWrapper) CreateAPIKey(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAPIKey(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAPIKey operation middleware
func (siw *ServerInterfaceWrapper) DeleteAPIKey(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "keyId" -------------
	var keyId string

	err = runtime.BindStyledParameterWithOptions("simple", "keyId", chi.URLParam(r, "keyId"), &keyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "keyId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAPIKey(w, r, keyId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListGameServerFleets operation middleware
func (siw *ServerInterfaceWrapper) ListGameServerFleets(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListGameServerFleets(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateGameServerFleet operation middleware
func (siw *ServerInterfaceWrapper) CreateGameServerFleet(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", chi.URLParam(r, "namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateGameServerFleet(w, r, namespace)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteGameServerFleet operation middleware
func (siw *ServerInterfaceWrapper) DeleteGameServerFleet(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace Namespace

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", chi.URLParam(r, "namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name Name

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteGameServerFleet(w, r, namespace, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGameServerFleet operation middleware
func (siw *ServerInterfaceWrapper) GetGameServerFleet(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace Namespace

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", chi.URLParam(r, "namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name Name

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGameServerFleet(w, r, namespace, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateGameServerFleet operation middleware
func (siw *ServerInterfaceWrapper) UpdateGameServerFleet(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace Namespace

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", chi.URLParam(r, "namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name Name

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateGameServerFleet(w, r, namespace, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListGameServers operation middleware
func (siw *ServerInterfaceWrapper) ListGameServers(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListGameServers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateGameServer operation middleware
func (siw *ServerInterfaceWrapper) CreateGameServer(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", chi.URLParam(r, "namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateGameServer(w, r, namespace)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteGameServer operation middleware
func (siw *ServerInterfaceWrapper) DeleteGameServer(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace Namespace

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", chi.URLParam(r, "namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name Name

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteGameServer(w, r, namespace, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGameServer operation middleware
func (siw *ServerInterfaceWrapper) GetGameServer(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace Namespace

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", chi.URLParam(r, "namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name Name

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGameServer(w, r, namespace, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateGameServerLifecycle operation middleware
func (siw *ServerInterfaceWrapper) UpdateGameServerLifecycle(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace Namespace

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", chi.URLParam(r, "namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name Name

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateGameServerLifecycle(w, r, namespace, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListActions operation middleware
func (siw *ServerInterfaceWrapper) ListActions(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace Namespace

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", chi.URLParam(r, "namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name Name

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListActions(w, r, namespace, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExecuteAction operation middleware
func (siw *ServerInterfaceWrapper) ExecuteAction(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace Namespace

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", chi.URLParam(r, "namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name Name

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// ------------- Path parameter "action" -------------
	var action string

	err = runtime.BindStyledParameterWithOptions("simple", "action", chi.URLParam(r, "action"), &action, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "action", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExecuteAction(w, r, namespace, name, action)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetConsole operation middleware
func (siw *ServerInterfaceWrapper) GetConsole(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace Namespace

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", chi.URLParam(r, "namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name Name

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetConsole(w, r, namespace, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetActionExecution operation middleware
func (siw *ServerInterfaceWrapper) GetActionExecution(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace Namespace

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", chi.URLParam(r, "namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name Name

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// ------------- Path parameter "executionId" -------------
	var executionId string

	err = runtime.BindStyledParameterWithOptions("simple", "executionId", chi.URLParam(r, "executionId"), &executionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "executionId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetActionExecution(w, r, namespace, name, executionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSFTPInfo operation middleware
func (siw *ServerInterfaceWrapper) GetSFTPInfo(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace Namespace

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", chi.URLParam(r, "namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name Name

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSFTPInfo(w, r, namespace, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSnapshots operation middleware
func (siw *ServerInterfaceWrapper) ListSnapshots(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace Namespace

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", chi.URLParam(r, "namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name Name

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSnapshots(w, r, namespace, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSnapshot operation middleware
func (siw *ServerInterfaceWrapper) CreateSnapshot(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace Namespace

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", chi.URLParam(r, "namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name Name

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSnapshot(w, r, namespace, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProfiles operation middleware
func (siw *ServerInterfaceWrapper) ListProfiles(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProfiles(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProfile operation middleware
func (siw *ServerInterfaceWrapper) GetProfile(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProfile(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthConfig operation middleware
func (siw *ServerInterfaceWrapper) GetAuthConfig(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadyz operation middleware
func (siw *ServerInterfaceWrapper) GetReadyz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadyz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/apikeys", wrapper.ListAPIKeys)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/apikeys", wrapper.CreateAPIKey)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/apikeys/{keyId}", wrapper.DeleteAPIKey)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/gameserverfleets", wrapper.ListGameServerFleets)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/gameserverfleets/{namespace}", wrapper.CreateGameServerFleet)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/gameserverfleets/{namespace}/{name}", wrapper.DeleteGameServerFleet)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/gameserverfleets/{namespace}/{name}", wrapper.GetGameServerFleet)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/v1/gameserverfleets/{namespace}/{name}", wrapper.UpdateGameServerFleet)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/gameservers", wrapper.ListGameServers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/gameservers/{namespace}", wrapper.CreateGameServer)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/gameservers/{namespace}/{name}", wrapper.DeleteGameServer)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/gameservers/{namespace}/{name}", wrapper.GetGameServer)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/v1/gameservers/{namespace}/{name}", wrapper.UpdateGameServerLifecycle)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/gameservers/{namespace}/{name}/actions", wrapper.ListActions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/gameservers/{namespace}/{name}/actions/{action}", wrapper.ExecuteAction)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/gameservers/{namespace}/{name}/console", wrapper.GetConsole)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/gameservers/{namespace}/{name}/executions/{executionId}", wrapper.GetActionExecution)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/gameservers/{namespace}/{name}/sftp", wrapper.GetSFTPInfo)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/gameservers/{namespace}/{name}/snapshots", wrapper.ListSnapshots)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/gameservers/{namespace}/{name}/snapshots", wrapper.CreateSnapshot)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/profiles", wrapper.ListProfiles)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/profiles/{name}", wrapper.GetProfile)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/config", wrapper.GetAuthConfig)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealthz)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/readyz", wrapper.GetReadyz)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xd73LbOJJ/lT7eVY2ToyVlJnuz59R8SDxJxptkorKSnauKXCeIbIlYkwAXAGVrUq66",
	"h7gnvCe5wh/+EyGJsh1nMp8ikyDQ6G50/7rRQD4HEc9yzpApGZx8DnIiSIYKhfnrV5Kh/pey4CTIiUqC",
	"MGDmmf0nDAT+s6AC4+BEiQLDQEYJZkR/o9a5bieVoGwZ3NyEpjeZk2hXl/b9If3e6MYy50yiofkFic/x",
	"nwVKpf+KOFPIzE+S5ymNiKKcDf8hOdPP6m7/TeAiOAn+dVjzY2jfyuFLIbiwQ8UoI0Fz3UlwEpyxFUlp",
	"DMINeBMGr7iY0zhG9hCjy2KxoBFFpiBHkVEpKWdSk/ErV694weIvT8U5Sl6ICIFxBQsz5k0YfGSkUAkX",
	"9Hd8ABqeFypBplyvUCmPbuk+1n0/H5+9wbVRc8FzFIpalYkEEoXxc0PegouMqOAkiInCY0WNmm8oXVh+",
	"8mLtUckwwOucCpS2wzap780PkoJpswY9wDP7B8ZwiWsJRCAI/AdGCmO4oiqBp6MnQdiTMubWrPeFWV6y",
	"S1W1NCEnSqFgElSCmhygEgTqXgw5isMRZrlaw08QpYVUKI6vaIyPgjCgCjPpHdo9IEKQtf5b8NTQiKzI",
	"gpNPwYriFYogDLRUiOL6J4kzyoKL0GNI3BM+1zzS/VnBnlqZ3It8WxLs98mlVa02Yz8kCM/HZ4aTK5IW",
	"CEcy4VcMOIsM024rv8OZ3Wl4RQTTP73GujbAnypbrzuy87zwCSGyc+5wn7OoEAJZ5PizIEWquUnSlF8F",
	"YaUFEgUlKf1dD4LXWrvoSv+27S48vGrx+vMBvDRuzlBH4pjaFTluUb3LDtmZjnUfgU8dtYbwwqgOXpMs",
	"1/wP/pIF/XTZdP7yGqPCz0+S07+jkNvmfEmt1a9H3uzRw8gMFYmJ2muB3xsy36Ei+iuZY+Shzwz36zbW",
	"RyRNUdxSKtuUvcF7IpaozvUUbsm4W6xI/xLaoM1HrVREFdK3ZrTsDrVZxj36CBUozZLzvJKKiAPH0US3",
	"zPcYWazfhcF5wZj9NSmiCDHGOAiDV4Sm5se582q9zHqPxeEVcymutiGuvoGzn70LsWPwtts4u/I7A1eW",
	"zSuBsvfq5ZzzFAmrtbhmqPsuDFiRzY1jLBv39IeFSk45W9BlyxJ8DjQoe8djTe+nYE4kjbTTpbH+h+TU",
	"mXbz4iUj87QG4LrRmZSFXrpBolQuT4ZD3d3gx8ul4EU+iHg2FEjSTA4zyojiZkm3V2A9/KZ8nq8ITfWI",
	"QNpgLjPtG+iiZBLjTKvn1lnsdYztaW4S9FuCKkEBL3QrQ5SGQuiahx4pNlnUgX1nP58CNS/h4/lbOKIL",
	"cM/KPh81IV4hqBF/anhSCmG31tbc3ZibT5MtWLLAqREvteV1II6Fo6yQCuYIlBn8uChUIfDRwdi1PdQb",
	"XIODIAeB2opE1kW3R3hNImXfABegBKEpZcvjafB4GsAy5XMJsogSIBKmgUJGmDp+PA0eVWiYsmUJkgfw",
	"PqM6+hFAWrDYvLwVNN4IsniKpvsSlR85YyM1ItcPrVv9ToLu4FEDVR2IrXuZwZcszjllHo0hcSxQygPR",
	"GBdNq0mZwiUKv2l7yVZ/J+Iw47sPJjrkfpDR9tJWOuCNVbTFL29w2zbzsfs1yXAs+IJa1bgjHGz2du9Q",
	"cNcXjYEnurmXh5uNtsDLdgy0H6z7lhpZok+FaUaWfj1dbeWzbyYRycmcprTstz3KnESXRe6HA3ry0v9K",
	"Gx8u8JXg2YSRXCZc+RvKhcr76m1EFC658ISvEz3YQnCmoGwERzhYDkASFs/5dQiLXIYgC7GiK5KGkGVc",
	"W5+MXL9FtlRJcPLD9/sjt/ao74i4jHWQPE8LMQf7cl7a2yXJrC2UFXGyPeLT0X/+h29MKvOUrLdGJshW",
	"VHCWOa3opV3OHHm0i0a+qWnfrzgQBvo9GF3bmAw4Ottz+ssTHxsrXW2PohcRSBQrFBBxpghlKOxgviXP",
	"57qtVVZPesysk3eonZ5HkU0O965WXY9PI3zHGVVeE1qjtK6q657FiqS3jsI0pf0NyljPy+e5XSJU7nRO",
	"3bwb8IXRa0VRgEmOYgxXCTIgoAU5sXKMOUqTY9Wmli7WYOHvvoWW0owqX4SZF16pZZg5S9DDxLm895fq",
	"XnPk1kmaMi99bl1sZnY4OpljLYAYStFBLlCikiAxxUiZcGRFW2LQ3B9owoKeAT4Xbom2GZTxgqnxtrUj",
	"6e/481ZEswEc6q4uetFUz2YfmqhBQwkeBza0G1A+XD3xZkG9eMMN9+Bww45r0UYz29LzO9t+DxNfpYjq",
	"nnBZs8cvnKbLBeWCqvVpSqTc6hPzGnZ64LHZyJE+Ix8GCrM8dYmi9si3EZ7XPPCcp3y5nuQCSXzKmdRR",
	"HFPe/Hjjsw27XeQ6Jp0ooQGOx/0JnurI8KNp5lnI5PojI2X2oq/D28z4nLcGCYNztJsWt86UbcssVpSe",
	"75RexJk1uQcyU0tivbvr3WpjpRHv6uLmQCtnltOYqCjZ7ksWJJUYdtCvjvMhQ7HE41x3YKDaQvcHMiJa",
	"YgN4z9K1dQvlzIBKIFGEucL4GRTskmkwu6CYxv7dvdEgCLcskp3kbihqg2cZZTTTqjUK78y/t3SB0Tpy",
	"GcT+9JBC8YkiQm1Prmnc43CqTHiRxjBHEDaJPADTKywFiXBRpJrLiucSSNmi/PTIIFQYC8yJwElSKB09",
	"hEZEqOH2KASTtIaJ4nmO8aNnoESBYJLfukNpn5cdkiWhbOBN8tE4xQ92f2eCepV4Ek/uhQZ2GsijONZf",
	"2RTZHBdcmCQnP5aOUjgawU/AcIXCxE4Hyc4rqXvU9gb2ScvuTVAheNpU/urloJI7DDdfdbln1sNXWCxp",
	"U6n7eaJ6HRy8hPypDGSrgza7NnY06nAVVkRQbdRl4CGjNdUdS7SvsvfRyZST+AVJCYtQnI27S2RMdXhj",
	"QxkaAV4rFIykcDau0pzLOoj9TsLbRofgwkUfRDoY1mxWsyxQIIuM2WjkorYmoBsAf5cWTWyzEomaAMIz",
	"uAtDTCi4EDwzjGiQ8Z0sPY2LNQc2RtoXB+7Rzm1YQZvVXSD2tigBXf5YHpBncRlnT2/Wxp6SnEQuf7GZ",
	"TrrW9tTZYojKhqEHftg2Hpt+akoYVNWJjrm8PXR3RwVfUc3CzS3Ss9hkYJ1PCsr88UV/6TUygPcRfJTd",
	"feHIY1kpntu/9UQWCtm2apKCKT90jAtBVCdy/fH7UdKv8kLPIS58VuFUcAZ4nQs0FXY2YedaxyAd32TP",
	"YbasNgOdD9qHp7/jtj39rRv0epB6S/620UVDzP5qK8qZdhxSkSzvP6OUzDG9YwHIPVVrhMHY5S871Uw2",
	"nTrekt40tWNcllvKLodj92+3gWAqIedC6bghL+YplQnGwO0eauUad3vAhtdmO7ye4hFP22VYH07Hje1C",
	"+9fHn8c97ZA3zdbh2rebhfQNOHn1YXzGFrw7YMKl8tWeOBHq18ykfIVGOi7x2wA6XkRDpLziIt6ZZN+A",
	"8q8+jK1GOSVyYciCRDps2q1JzWBcaroz3J+DNBN35DS+a1Dv29hsoqJumsiZt9qUfz96Tb2G0BngneVA",
	"d7YHDukZYNlXdSRGhUajE+0eK9f8BtfPC5v5bcvtLS5JtAaSUiKNkylLR9s1Mc8gFxqnwuy5K7I2j0/g",
	"BRKBYhaEtrw+QRIbnXIF9v91/Hx8dvwGG9DHUlNVw/jJqktgGnU5RymPSAoxrjDluYlCOEvXOoA1YMAY",
	"JVeb4wZLlMrNUIZM/1imKOZvv30AxS/RetqkyAiTIZjqCpt/rhhzNLMP/nswGMwe6eZTlpEooawsiZAD",
	"mFUTnzVTM0B06J9u4bkcTFlrLobozcncmP0nawqMa4hUrXTBj2/gteBFrpeESBuFU42aqW5gd/5y8sFQ",
	"oanJCCNLvWgbVkKGNgclQ3CBjAyBsAYSGUzZ8zSFCmdDwWKtL0OS0+Hqyawskd8UKl5r1sBVgsIU9GM8",
	"mLIp+6A9VMyjwoiZ2uLwx49dtKLNmChU8vhxFbtp6k2OgERqyo4kIsxiHskhEVFCFUaqEKiJOY44W1ms",
	"JwdZPHs0AJdsELxQaDMAS2QoiMJ4ykxQRNUzwJgqmz7KMYIFFVKF+m8GAsv2VoKKKmM93lnNObWpCxin",
	"hBlCg8bGfvBkMBqMzJ5ojozkNDgJfhiMBj8YS6YSs4IdE4e21MxCWvRY4bdUKiBpWmmUyWDwQoHESKCy",
	"BeESjkw5TrV67FYL5ewsdp3YKi0ZbJx0+X40OuhoRb9yCXtGohNmdQ9dmOnxRTU7/c3T0ZNtA1SkD1tn",
	"Q8xHP+z/qD5XY+xqkWVEe3BLRUVCGCiyNMWN+pFh2oXxkj63/NqpCRBgeFWblF3iaJbNBRX0eMHj9b2d",
	"cvFV5t20/a1GkzcdbXhybyS0z1P4Dtw4XrmTFXBUn29oHm8wwh3tF27jzNZXUSI701ID/Fp0E24u/OHn",
	"S1yfxTdWs1JUnsjxZ/N8KHDFLxEI66dl9qtKy5qH8j55j84ZQg46NnfRUZ+nnqJcR6wlP34w4egvnu7/",
	"ojrk1pbmuWV2X2lqx2r9qnWq++35xtaSRhSCS2neNQpSfaZ889MHsembO8sHGHfHktsJvmuoF+WkS5E4",
	"LuwUyPBzxVSz1vzW3K1ha8s3ZlzWI7t8M8aNkuDmQhxoqINgz5A02mjQWCh+XJk7DbYSImJkGD8CugCq",
	"qgKdKcNrKtUAdFeizCfHrWyyqZM2zQxuqzYOy/rpaTEa/YA/wchCGJ8P6pYL7DcTtzthe/Fl/FxHKx/W",
	"x3mHb6uU1Z2odIPfljNblEUkt1xp9ncP59YqU7Ms0zpNlWw8l30c3l6V9jGkbjKsD5jfhL0aB/3coJ2U",
	"5cK34gSdbLZqQej3ca+19Op9ua5E2nJ7jeoPIbTRw5uFGBWhqbyrnDTDdwgpLzfy2yT8bfL+1911KXBU",
	"luz9u/NtZq9+ymatUpUZZGStPU6UELbE+BkQtgZu8tJmD96e/97cgZ+yw1yWrWv6WqryxX2XLbfo5cAe",
	"VFMt22OnYH9gB3a3NTQxdT6HObyDYP7tEP5Dg/tDcH0zm3hv6L7VaS2IJke2SeNOGL8vvN+LpL9lEP31",
	"8LNPz1onUL5NAL2xLXdLZb4djD4MLf9hgHJT6t8kXO4j80ORM8zXDXukQyO3NboDSv95UPQ+43CPMLqf",
	"8A5B1J2C1z2o2lMDOzMSn+2tg51N2S2R+JRNUJnT6LNq1BNbOz0Dzrrl0p2CaqqmbFsN9UQRpRtPXGhh",
	"74ByBdWFHJhaoymbY8QzlDBz1Wx2I69LlvZKjqp2zfWUuWJsqlz5NZhdR7fZGBNFjnOzZae/g0JirBeW",
	"3f09jlJexFOmOMhC5sjKXqU7raqFGVsuPOoTn9Slvn+GGGWjLPyrxSm7QpTm4v3TBiqG/82p1hbm7hBj",
	"2DgZvyOwsY2gOgfkbq1oEjUn0tafUSXLCgP/xrQb8RvwVne6K2B7HFWzseT+HVXECqnTa2MTyz25hWYM",
	"P9sfOyIse02S2am0ba2tbmrHpgvsaIbrwzHzAXQj9MZppBz/QYK03gWrjduYMpTSnB0IfsE05a5KT/6L",
	"p661e8/pve73d6/V8m36R65GqLxJy90d9nWitEpTSzHfZYFEnEl38Y7XdH7Ml4LEaG7bIfAbzic8ukSl",
	"YSHDyDFDIMk03knpygBG3SPwQuWF2RGZMlt4ppuUbyOeZYTF0m4WOn2Ask5Xg58YF5RhDJRNmSuh0kDt",
	"2NXd6fm4zo7LzwZZPIMjrUAxGFi70OtFnkxZlJq7YiWyWMJMRJzNhrOcsuUsrI7h2XcpX86GpsVxKYrZ",
	"cGYx32w4M3fVzDSUcnW/EkqrYC4gAi4gocsEhQ9tvUZ16hj+FTzHE6uqGxWzV1RFiRbN2HFRwv/9z/82",
	"RG3lCygVcRXaf16c4qTTmX1jlZUCPGSVVZZDDj9Xv10BzdaY2iT2jN4Zf1v5JWzcZ9lRr+6Vl1/JCTWm",
	"ecfynNGXsva9TP09hunE40ZUcVeIU9535NWjc1RFeaexqY1v2G3KFhyOEi5VaErmQyir10Moi9ddYXEb",
	"B10lXLYO57mL/CTMmlc/DTRlswH8wqVzA6YwX4fL9RG/6phjffxjZr4rVb+s5H02ZZHAGJmiJJXeXo5l",
	"xLXpf1PMUTBUKGFi6k0HUBrrKdtmraFk1dPRU3sJTeOIdnUFjalcCafMHC1wk69fGi4YPpua7Qa9w7og",
	"mdgC4ynLy+NxGMMa1RZ/UR25+MYTY9U8PIvOp5nfiMPQ69pL/t2j2vp03c64tmrWjWe9oeukcWjvzxG8",
	"to5wHhDC1gz2RKKts41OkjXrttdWVzt1ZQeeNMPeQNJ20jiW+hUEdc8bZpV8PMu/5FRrv+wrbX7Jxllg",
	"j9gby7c8gdJvP925SglH5TWp1lv5Dz6UrR9sI728F/PQnfSKCfe1lZ7XMy/5XzHDy/7GPmPf7anxlsze",
	"a1T1q3774X8YbNsSYldoJVK7Rzhb50e3CapQiY7R3W3cewEq2XkTttlOsr254+4Ddz6rxFbVKeLItC13",
	"SnTXH89MAsOUMrsu7ChbUFfjHvEvGY/Uo2z5v13aE26drAxOPl00RdJtDjGVEV+haB0FKFTi5JMgSVXy",
	"+17ZfD8awfs3QO2h3XJD0O5JUVlusvnY+IsbYS8PFV6rYZ4SusG9xj18l55LBjo8O90kjqR0hTv59pau",
	"kKE0+f55U5st8Y5X5o6Cu7NK96I10QABqM5ve1h3bgf8epwztO7knCaR7mFd+/PPrROwny40PGkcv7UP",
	"mueEP11oo1kVrn3quNjNo7itA6cnw6E5q6tj3JO/jv46MjjHEdm5mMdaDrsoIEowupS1rXcz0vTt/B+Y",
	"mkvOfWpm0v3wtW8zzJ56RTcT10EzgNjdjydDVBJRbdLs+r7CrD4yahi0uxNbjevr4VV5psb7eRlP+74c",
	"1zCji7IaSecqF11/WubrPKJzh7x8A1Ynpm4ubv4/AAD//xyjKJIrbgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
