# CS2 agent - uses locally built binary
FROM alpine:latest
WORKDIR /
RUN apk add --no-cache ca-certificates
COPY bin/agent-cs2 .
RUN adduser -D -u 65532 minato
USER 65532:65532

EXPOSE 9876 9090
ENTRYPOINT ["/agent-cs2"]
