// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: minato/agent/v1/agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActionState int32

const (
	ActionState_ACTION_STATE_UNSPECIFIED ActionState = 0
	ActionState_ACTION_STATE_PENDING     ActionState = 1
	ActionState_ACTION_STATE_RUNNING     ActionState = 2
	ActionState_ACTION_STATE_SUCCEEDED   ActionState = 3
	ActionState_ACTION_STATE_FAILED      ActionState = 4
	ActionState_ACTION_STATE_TIMED_OUT   ActionState = 5
	ActionState_ACTION_STATE_REJECTED    ActionState = 6
)

// Enum value maps for ActionState.
var (
	ActionState_name = map[int32]string{
		0: "ACTION_STATE_UNSPECIFIED",
		1: "ACTION_STATE_PENDING",
		2: "ACTION_STATE_RUNNING",
		3: "ACTION_STATE_SUCCEEDED",
		4: "ACTION_STATE_FAILED",
		5: "ACTION_STATE_TIMED_OUT",
		6: "ACTION_STATE_REJECTED",
	}
	ActionState_value = map[string]int32{
		"ACTION_STATE_UNSPECIFIED": 0,
		"ACTION_STATE_PENDING":     1,
		"ACTION_STATE_RUNNING":     2,
		"ACTION_STATE_SUCCEEDED":   3,
		"ACTION_STATE_FAILED":      4,
		"ACTION_STATE_TIMED_OUT":   5,
		"ACTION_STATE_REJECTED":    6,
	}
)

func (x ActionState) Enum() *ActionState {
	p := new(ActionState)
	*p = x
	return p
}

func (x ActionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionState) Descriptor() protoreflect.EnumDescriptor {
	return file_minato_agent_v1_agent_proto_enumTypes[0].Descriptor()
}

func (ActionState) Type() protoreflect.EnumType {
	return &file_minato_agent_v1_agent_proto_enumTypes[0]
}

func (x ActionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionState.Descriptor instead.
func (ActionState) EnumDescriptor() ([]byte, []int) {
	return file_minato_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_minato_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minato_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_minato_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

type InfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Actions       []*ActionSchema        `protobuf:"bytes,3,rep,name=actions,proto3" json:"actions,omitempty"`
	Metrics       []*MetricDescriptor    `protobuf:"bytes,4,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_minato_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minato_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_minato_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *InfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InfoResponse) GetActions() []*ActionSchema {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *InfoResponse) GetMetrics() []*MetricDescriptor {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_minato_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minato_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_minato_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_minato_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minato_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_minato_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *HealthResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type ShutdownRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TimeoutSeconds int32                  `protobuf:"varint,1,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	DrainReason    string                 `protobuf:"bytes,2,opt,name=drain_reason,json=drainReason,proto3" json:"drain_reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_minato_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minato_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_minato_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ShutdownRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ShutdownRequest) GetDrainReason() string {
	if x != nil {
		return x.DrainReason
	}
	return ""
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_minato_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minato_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_minato_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ShutdownResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ShutdownResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PlayersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayersRequest) Reset() {
	*x = PlayersRequest{}
	mi := &file_minato_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayersRequest) ProtoMessage() {}

func (x *PlayersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minato_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayersRequest.ProtoReflect.Descriptor instead.
func (*PlayersRequest) Descriptor() ([]byte, []int) {
	return file_minato_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

type PlayersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Online        int32                  `protobuf:"varint,1,opt,name=online,proto3" json:"online,omitempty"`
	Capacity      int32                  `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Players       []*Player              `protobuf:"bytes,3,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayersResponse) Reset() {
	*x = PlayersResponse{}
	mi := &file_minato_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayersResponse) ProtoMessage() {}

func (x *PlayersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minato_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayersResponse.ProtoReflect.Descriptor instead.
func (*PlayersResponse) Descriptor() ([]byte, []int) {
	return file_minato_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *PlayersResponse) GetOnline() int32 {
	if x != nil {
		return x.Online
	}
	return 0
}

func (x *PlayersResponse) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *PlayersResponse) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	JoinedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_minato_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_minato_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_minato_agent_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Player) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

type ExecuteActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionName    string                 `protobuf:"bytes,1,opt,name=action_name,json=actionName,proto3" json:"action_name,omitempty"`
	Params        map[string]string      `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ExecutionId   string                 `protobuf:"bytes,3,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteActionRequest) Reset() {
	*x = ExecuteActionRequest{}
	mi := &file_minato_agent_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteActionRequest) ProtoMessage() {}

func (x *ExecuteActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minato_agent_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteActionRequest.ProtoReflect.Descriptor instead.
func (*ExecuteActionRequest) Descriptor() ([]byte, []int) {
	return file_minato_agent_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *ExecuteActionRequest) GetActionName() string {
	if x != nil {
		return x.ActionName
	}
	return ""
}

func (x *ExecuteActionRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ExecuteActionRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type ExecuteActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         ActionState            `protobuf:"varint,1,opt,name=state,proto3,enum=minato.agent.v1.ActionState" json:"state,omitempty"`
	Result        *anypb.Any             `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteActionResponse) Reset() {
	*x = ExecuteActionResponse{}
	mi := &file_minato_agent_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteActionResponse) ProtoMessage() {}

func (x *ExecuteActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minato_agent_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteActionResponse.ProtoReflect.Descriptor instead.
func (*ExecuteActionResponse) Descriptor() ([]byte, []int) {
	return file_minato_agent_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *ExecuteActionResponse) GetState() ActionState {
	if x != nil {
		return x.State
	}
	return ActionState_ACTION_STATE_UNSPECIFIED
}

func (x *ExecuteActionResponse) GetResult() *anypb.Any {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ExecuteActionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ConsoleClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ConsoleClientMessage_Command
	//	*ConsoleClientMessage_Ping
	Payload       isConsoleClientMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsoleClientMessage) Reset() {
	*x = ConsoleClientMessage{}
	mi := &file_minato_agent_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleClientMessage) ProtoMessage() {}

func (x *ConsoleClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_minato_agent_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleClientMessage.ProtoReflect.Descriptor instead.
func (*ConsoleClientMessage) Descriptor() ([]byte, []int) {
	return file_minato_agent_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *ConsoleClientMessage) GetPayload() isConsoleClientMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ConsoleClientMessage) GetCommand() *ConsoleCommand {
	if x != nil {
		if x, ok := x.Payload.(*ConsoleClientMessage_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *ConsoleClientMessage) GetPing() *ConsolePing {
	if x != nil {
		if x, ok := x.Payload.(*ConsoleClientMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isConsoleClientMessage_Payload interface {
	isConsoleClientMessage_Payload()
}

type ConsoleClientMessage_Command struct {
	Command *ConsoleCommand `protobuf:"bytes,1,opt,name=command,proto3,oneof"`
}

type ConsoleClientMessage_Ping struct {
	Ping *ConsolePing `protobuf:"bytes,2,opt,name=ping,proto3,oneof"`
}

func (*ConsoleClientMessage_Command) isConsoleClientMessage_Payload() {}

func (*ConsoleClientMessage_Ping) isConsoleClientMessage_Payload() {}

type ConsoleServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ConsoleServerMessage_Log
	//	*ConsoleServerMessage_Response
	//	*ConsoleServerMessage_Status
	//	*ConsoleServerMessage_Error
	Payload       isConsoleServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsoleServerMessage) Reset() {
	*x = ConsoleServerMessage{}
	mi := &file_minato_agent_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleServerMessage) ProtoMessage() {}

func (x *ConsoleServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_minato_agent_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleServerMessage.ProtoReflect.Descriptor instead.
func (*ConsoleServerMessage) Descriptor() ([]byte, []int) {
	return file_minato_agent_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *ConsoleServerMessage) GetPayload() isConsoleServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ConsoleServerMessage) GetLog() *ConsoleLog {
	if x != nil {
		if x, ok := x.Payload.(*ConsoleServerMessage_Log); ok {
			return x.Log
		}
	}
	return nil
}

func (x *ConsoleServerMessage) GetResponse() *ConsoleResponse {
	if x != nil {
		if x, ok := x.Payload.(*ConsoleServerMessage_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *ConsoleServerMessage) GetStatus() *ConsoleStatus {
	if x != nil {
		if x, ok := x.Payload.(*ConsoleServerMessage_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *ConsoleServerMessage) GetError() *ConsoleError {
	if x != nil {
		if x, ok := x.Payload.(*ConsoleServerMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isConsoleServerMessage_Payload interface {
	isConsoleServerMessage_Payload()
}

type ConsoleServerMessage_Log struct {
	Log *ConsoleLog `protobuf:"bytes,1,opt,name=log,proto3,oneof"`
}

type ConsoleServerMessage_Response struct {
	Response *ConsoleResponse `protobuf:"bytes,2,opt,name=response,proto3,oneof"`
}

type ConsoleServerMessage_Status struct {
	Status *ConsoleStatus `protobuf:"bytes,3,opt,name=status,proto3,oneof"`
}

type ConsoleServerMessage_Error struct {
	Error *ConsoleError `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*ConsoleServerMessage_Log) isConsoleServerMessage_Payload() {}

func (*ConsoleServerMessage_Response) isConsoleServerMessage_Payload() {}

func (*ConsoleServerMessage_Status) isConsoleServerMessage_Payload() {}

func (*ConsoleServerMessage_Error) isConsoleServerMessage_Payload() {}

type ActionSchema struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Name          string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                  `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Params        map[string]*ParamSchema `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionSchema) Reset() {
	*x = ActionSchema{}
	mi := &file_minato_agent_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionSchema) ProtoMessage() {}

func (x *ActionSchema) ProtoReflect() protoreflect.Message {
	mi := &file_minato_agent_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionSchema.ProtoReflect.Descriptor instead.
func (*ActionSchema) Descriptor() ([]byte, []int) {
	return file_minato_agent_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *ActionSchema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActionSchema) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ActionSchema) GetParams() map[string]*ParamSchema {
	if x != nil {
		return x.Params
	}
	return nil
}

type ParamSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Required      bool                   `protobuf:"varint,2,opt,name=required,proto3" json:"required,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Default       string                 `protobuf:"bytes,4,opt,name=default,proto3" json:"default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamSchema) Reset() {
	*x = ParamSchema{}
	mi := &file_minato_agent_v1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamSchema) ProtoMessage() {}

func (x *ParamSchema) ProtoReflect() protoreflect.Message {
	mi := &file_minato_agent_v1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamSchema.ProtoReflect.Descriptor instead.
func (*ParamSchema) Descriptor() ([]byte, []int) {
	return file_minato_agent_v1_agent_proto_rawDescGZIP(), []int{14}
}

func (x *ParamSchema) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ParamSchema) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ParamSchema) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ParamSchema) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

type MetricDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Unit          string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricDescriptor) Reset() {
	*x = MetricDescriptor{}
	mi := &file_minato_agent_v1_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricDescriptor) ProtoMessage() {}

func (x *MetricDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_minato_agent_v1_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricDescriptor.ProtoReflect.Descriptor instead.
func (*MetricDescriptor) Descriptor() ([]byte, []int) {
	return file_minato_agent_v1_agent_proto_rawDescGZIP(), []int{15}
}

func (x *MetricDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricDescriptor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MetricDescriptor) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

type ConsoleCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RconCommand   string                 `protobuf:"bytes,1,opt,name=rcon_command,json=rconCommand,proto3" json:"rcon_command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsoleCommand) Reset() {
	*x = ConsoleCommand{}
	mi := &file_minato_agent_v1_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleCommand) ProtoMessage() {}

func (x *ConsoleCommand) ProtoReflect() protoreflect.Message {
	mi := &file_minato_agent_v1_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleCommand.ProtoReflect.Descriptor instead.
func (*ConsoleCommand) Descriptor() ([]byte, []int) {
	return file_minato_agent_v1_agent_proto_rawDescGZIP(), []int{16}
}

func (x *ConsoleCommand) GetRconCommand() string {
	if x != nil {
		return x.RconCommand
	}
	return ""
}

type ConsolePing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsolePing) Reset() {
	*x = ConsolePing{}
	mi := &file_minato_agent_v1_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsolePing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsolePing) ProtoMessage() {}

func (x *ConsolePing) ProtoReflect() protoreflect.Message {
	mi := &file_minato_agent_v1_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsolePing.ProtoReflect.Descriptor instead.
func (*ConsolePing) Descriptor() ([]byte, []int) {
	return file_minato_agent_v1_agent_proto_rawDescGZIP(), []int{17}
}

func (x *ConsolePing) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ConsoleLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          string                 `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsoleLog) Reset() {
	*x = ConsoleLog{}
	mi := &file_minato_agent_v1_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleLog) ProtoMessage() {}

func (x *ConsoleLog) ProtoReflect() protoreflect.Message {
	mi := &file_minato_agent_v1_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleLog.ProtoReflect.Descriptor instead.
func (*ConsoleLog) Descriptor() ([]byte, []int) {
	return file_minato_agent_v1_agent_proto_rawDescGZIP(), []int{18}
}

func (x *ConsoleLog) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

type ConsoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsoleResponse) Reset() {
	*x = ConsoleResponse{}
	mi := &file_minato_agent_v1_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleResponse) ProtoMessage() {}

func (x *ConsoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minato_agent_v1_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleResponse.ProtoReflect.Descriptor instead.
func (*ConsoleResponse) Descriptor() ([]byte, []int) {
	return file_minato_agent_v1_agent_proto_rawDescGZIP(), []int{19}
}

func (x *ConsoleResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type ConsoleStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsoleStatus) Reset() {
	*x = ConsoleStatus{}
	mi := &file_minato_agent_v1_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleStatus) ProtoMessage() {}

func (x *ConsoleStatus) ProtoReflect() protoreflect.Message {
	mi := &file_minato_agent_v1_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleStatus.ProtoReflect.Descriptor instead.
func (*ConsoleStatus) Descriptor() ([]byte, []int) {
	return file_minato_agent_v1_agent_proto_rawDescGZIP(), []int{20}
}

func (x *ConsoleStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type ConsoleError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsoleError) Reset() {
	*x = ConsoleError{}
	mi := &file_minato_agent_v1_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleError) ProtoMessage() {}

func (x *ConsoleError) ProtoReflect() protoreflect.Message {
	mi := &file_minato_agent_v1_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleError.ProtoReflect.Descriptor instead.
func (*ConsoleError) Descriptor() ([]byte, []int) {
	return file_minato_agent_v1_agent_proto_rawDescGZIP(), []int{21}
}

func (x *ConsoleError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_minato_agent_v1_agent_proto protoreflect.FileDescriptor

const file_minato_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x1bminato/agent/v1/agent.proto\x12\x0fminato.agent.v1\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\r\n" +
	"\vInfoRequest\"\xb2\x01\n" +
	"\fInfoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x127\n" +
	"\aactions\x18\x03 \x03(\v2\x1d.minato.agent.v1.ActionSchemaR\aactions\x12;\n" +
	"\ametrics\x18\x04 \x03(\v2!.minato.agent.v1.MetricDescriptorR\ametrics\"\x0f\n" +
	"\rHealthRequest\"\xc4\x01\n" +
	"\x0eHealthResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12F\n" +
	"\adetails\x18\x03 \x03(\v2,.minato.agent.v1.HealthResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"]\n" +
	"\x0fShutdownRequest\x12'\n" +
	"\x0ftimeout_seconds\x18\x01 \x01(\x05R\x0etimeoutSeconds\x12!\n" +
	"\fdrain_reason\x18\x02 \x01(\tR\vdrainReason\"B\n" +
	"\x10ShutdownResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x10\n" +
	"\x0ePlayersRequest\"x\n" +
	"\x0fPlayersResponse\x12\x16\n" +
	"\x06online\x18\x01 \x01(\x05R\x06online\x12\x1a\n" +
	"\bcapacity\x18\x02 \x01(\x05R\bcapacity\x121\n" +
	"\aplayers\x18\x03 \x03(\v2\x17.minato.agent.v1.PlayerR\aplayers\"e\n" +
	"\x06Player\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x127\n" +
	"\tjoined_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\"\xe0\x01\n" +
	"\x14ExecuteActionRequest\x12\x1f\n" +
	"\vaction_name\x18\x01 \x01(\tR\n" +
	"actionName\x12I\n" +
	"\x06params\x18\x02 \x03(\v21.minato.agent.v1.ExecuteActionRequest.ParamsEntryR\x06params\x12!\n" +
	"\fexecution_id\x18\x03 \x01(\tR\vexecutionId\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8f\x01\n" +
	"\x15ExecuteActionResponse\x122\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1c.minato.agent.v1.ActionStateR\x05state\x12,\n" +
	"\x06result\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x06result\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x92\x01\n" +
	"\x14ConsoleClientMessage\x12;\n" +
	"\acommand\x18\x01 \x01(\v2\x1f.minato.agent.v1.ConsoleCommandH\x00R\acommand\x122\n" +
	"\x04ping\x18\x02 \x01(\v2\x1c.minato.agent.v1.ConsolePingH\x00R\x04pingB\t\n" +
	"\apayload\"\x83\x02\n" +
	"\x14ConsoleServerMessage\x12/\n" +
	"\x03log\x18\x01 \x01(\v2\x1b.minato.agent.v1.ConsoleLogH\x00R\x03log\x12>\n" +
	"\bresponse\x18\x02 \x01(\v2 .minato.agent.v1.ConsoleResponseH\x00R\bresponse\x128\n" +
	"\x06status\x18\x03 \x01(\v2\x1e.minato.agent.v1.ConsoleStatusH\x00R\x06status\x125\n" +
	"\x05error\x18\x04 \x01(\v2\x1d.minato.agent.v1.ConsoleErrorH\x00R\x05errorB\t\n" +
	"\apayload\"\xe0\x01\n" +
	"\fActionSchema\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12A\n" +
	"\x06params\x18\x03 \x03(\v2).minato.agent.v1.ActionSchema.ParamsEntryR\x06params\x1aW\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.minato.agent.v1.ParamSchemaR\x05value:\x028\x01\"y\n" +
	"\vParamSchema\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\brequired\x18\x02 \x01(\bR\brequired\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\adefault\x18\x04 \x01(\tR\adefault\"\\\n" +
	"\x10MetricDescriptor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\"3\n" +
	"\x0eConsoleCommand\x12!\n" +
	"\frcon_command\x18\x01 \x01(\tR\vrconCommand\"'\n" +
	"\vConsolePing\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\" \n" +
	"\n" +
	"ConsoleLog\x12\x12\n" +
	"\x04line\x18\x01 \x01(\tR\x04line\"-\n" +
	"\x0fConsoleResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse\"%\n" +
	"\rConsoleStatus\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\"(\n" +
	"\fConsoleError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage*\xcb\x01\n" +
	"\vActionState\x12\x1c\n" +
	"\x18ACTION_STATE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ACTION_STATE_PENDING\x10\x01\x12\x18\n" +
	"\x14ACTION_STATE_RUNNING\x10\x02\x12\x1a\n" +
	"\x16ACTION_STATE_SUCCEEDED\x10\x03\x12\x17\n" +
	"\x13ACTION_STATE_FAILED\x10\x04\x12\x1a\n" +
	"\x16ACTION_STATE_TIMED_OUT\x10\x05\x12\x19\n" +
	"\x15ACTION_STATE_REJECTED\x10\x062\x82\x04\n" +
	"\x05Agent\x12C\n" +
	"\x04Info\x12\x1c.minato.agent.v1.InfoRequest\x1a\x1d.minato.agent.v1.InfoResponse\x12N\n" +
	"\vHealthCheck\x12\x1e.minato.agent.v1.HealthRequest\x1a\x1f.minato.agent.v1.HealthResponse\x12V\n" +
	"\x0fPrepareShutdown\x12 .minato.agent.v1.ShutdownRequest\x1a!.minato.agent.v1.ShutdownResponse\x12O\n" +
	"\n" +
	"GetPlayers\x12\x1f.minato.agent.v1.PlayersRequest\x1a .minato.agent.v1.PlayersResponse\x12^\n" +
	"\rExecuteAction\x12%.minato.agent.v1.ExecuteActionRequest\x1a&.minato.agent.v1.ExecuteActionResponse\x12[\n" +
	"\aConsole\x12%.minato.agent.v1.ConsoleClientMessage\x1a%.minato.agent.v1.ConsoleServerMessage(\x010\x01BBZ@github.com/7k-minato/minato/api/agent/v1/minato/agent/v1;agentv1b\x06proto3"

var (
	file_minato_agent_v1_agent_proto_rawDescOnce sync.Once
	file_minato_agent_v1_agent_proto_rawDescData []byte
)

func file_minato_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_minato_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_minato_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_minato_agent_v1_agent_proto_rawDesc), len(file_minato_agent_v1_agent_proto_rawDesc)))
	})
	return file_minato_agent_v1_agent_proto_rawDescData
}

var file_minato_agent_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_minato_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_minato_agent_v1_agent_proto_goTypes = []any{
	(ActionState)(0),              // 0: minato.agent.v1.ActionState
	(*InfoRequest)(nil),           // 1: minato.agent.v1.InfoRequest
	(*InfoResponse)(nil),          // 2: minato.agent.v1.InfoResponse
	(*HealthRequest)(nil),         // 3: minato.agent.v1.HealthRequest
	(*HealthResponse)(nil),        // 4: minato.agent.v1.HealthResponse
	(*ShutdownRequest)(nil),       // 5: minato.agent.v1.ShutdownRequest
	(*ShutdownResponse)(nil),      // 6: minato.agent.v1.ShutdownResponse
	(*PlayersRequest)(nil),        // 7: minato.agent.v1.PlayersRequest
	(*PlayersResponse)(nil),       // 8: minato.agent.v1.PlayersResponse
	(*Player)(nil),                // 9: minato.agent.v1.Player
	(*ExecuteActionRequest)(nil),  // 10: minato.agent.v1.ExecuteActionRequest
	(*ExecuteActionResponse)(nil), // 11: minato.agent.v1.ExecuteActionResponse
	(*ConsoleClientMessage)(nil),  // 12: minato.agent.v1.ConsoleClientMessage
	(*ConsoleServerMessage)(nil),  // 13: minato.agent.v1.ConsoleServerMessage
	(*ActionSchema)(nil),          // 14: minato.agent.v1.ActionSchema
	(*ParamSchema)(nil),           // 15: minato.agent.v1.ParamSchema
	(*MetricDescriptor)(nil),      // 16: minato.agent.v1.MetricDescriptor
	(*ConsoleCommand)(nil),        // 17: minato.agent.v1.ConsoleCommand
	(*ConsolePing)(nil),           // 18: minato.agent.v1.ConsolePing
	(*ConsoleLog)(nil),            // 19: minato.agent.v1.ConsoleLog
	(*ConsoleResponse)(nil),       // 20: minato.agent.v1.ConsoleResponse
	(*ConsoleStatus)(nil),         // 21: minato.agent.v1.ConsoleStatus
	(*ConsoleError)(nil),          // 22: minato.agent.v1.ConsoleError
	nil,                           // 23: minato.agent.v1.HealthResponse.DetailsEntry
	nil,                           // 24: minato.agent.v1.ExecuteActionRequest.ParamsEntry
	nil,                           // 25: minato.agent.v1.ActionSchema.ParamsEntry
	(*timestamppb.Timestamp)(nil), // 26: google.protobuf.Timestamp
	(*anypb.Any)(nil),             // 27: google.protobuf.Any
}
var file_minato_agent_v1_agent_proto_depIdxs = []int32{
	14, // 0: minato.agent.v1.InfoResponse.actions:type_name -> minato.agent.v1.ActionSchema
	16, // 1: minato.agent.v1.InfoResponse.metrics:type_name -> minato.agent.v1.MetricDescriptor
	23, // 2: minato.agent.v1.HealthResponse.details:type_name -> minato.agent.v1.HealthResponse.DetailsEntry
	9,  // 3: minato.agent.v1.PlayersResponse.players:type_name -> minato.agent.v1.Player
	26, // 4: minato.agent.v1.Player.joined_at:type_name -> google.protobuf.Timestamp
	24, // 5: minato.agent.v1.ExecuteActionRequest.params:type_name -> minato.agent.v1.ExecuteActionRequest.ParamsEntry
	0,  // 6: minato.agent.v1.ExecuteActionResponse.state:type_name -> minato.agent.v1.ActionState
	27, // 7: minato.agent.v1.ExecuteActionResponse.result:type_name -> google.protobuf.Any
	17, // 8: minato.agent.v1.ConsoleClientMessage.command:type_name -> minato.agent.v1.ConsoleCommand
	18, // 9: minato.agent.v1.ConsoleClientMessage.ping:type_name -> minato.agent.v1.ConsolePing
	19, // 10: minato.agent.v1.ConsoleServerMessage.log:type_name -> minato.agent.v1.ConsoleLog
	20, // 11: minato.agent.v1.ConsoleServerMessage.response:type_name -> minato.agent.v1.ConsoleResponse
	21, // 12: minato.agent.v1.ConsoleServerMessage.status:type_name -> minato.agent.v1.ConsoleStatus
	22, // 13: minato.agent.v1.ConsoleServerMessage.error:type_name -> minato.agent.v1.ConsoleError
	25, // 14: minato.agent.v1.ActionSchema.params:type_name -> minato.agent.v1.ActionSchema.ParamsEntry
	15, // 15: minato.agent.v1.ActionSchema.ParamsEntry.value:type_name -> minato.agent.v1.ParamSchema
	1,  // 16: minato.agent.v1.Agent.Info:input_type -> minato.agent.v1.InfoRequest
	3,  // 17: minato.agent.v1.Agent.HealthCheck:input_type -> minato.agent.v1.HealthRequest
	5,  // 18: minato.agent.v1.Agent.PrepareShutdown:input_type -> minato.agent.v1.ShutdownRequest
	7,  // 19: minato.agent.v1.Agent.GetPlayers:input_type -> minato.agent.v1.PlayersRequest
	10, // 20: minato.agent.v1.Agent.ExecuteAction:input_type -> minato.agent.v1.ExecuteActionRequest
	12, // 21: minato.agent.v1.Agent.Console:input_type -> minato.agent.v1.ConsoleClientMessage
	2,  // 22: minato.agent.v1.Agent.Info:output_type -> minato.agent.v1.InfoResponse
	4,  // 23: minato.agent.v1.Agent.HealthCheck:output_type -> minato.agent.v1.HealthResponse
	6,  // 24: minato.agent.v1.Agent.PrepareShutdown:output_type -> minato.agent.v1.ShutdownResponse
	8,  // 25: minato.agent.v1.Agent.GetPlayers:output_type -> minato.agent.v1.PlayersResponse
	11, // 26: minato.agent.v1.Agent.ExecuteAction:output_type -> minato.agent.v1.ExecuteActionResponse
	13, // 27: minato.agent.v1.Agent.Console:output_type -> minato.agent.v1.ConsoleServerMessage
	22, // [22:28] is the sub-list for method output_type
	16, // [16:22] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_minato_agent_v1_agent_proto_init() }
func file_minato_agent_v1_agent_proto_init() {
	if File_minato_agent_v1_agent_proto != nil {
		return
	}
	file_minato_agent_v1_agent_proto_msgTypes[11].OneofWrappers = []any{
		(*ConsoleClientMessage_Command)(nil),
		(*ConsoleClientMessage_Ping)(nil),
	}
	file_minato_agent_v1_agent_proto_msgTypes[12].OneofWrappers = []any{
		(*ConsoleServerMessage_Log)(nil),
		(*ConsoleServerMessage_Response)(nil),
		(*ConsoleServerMessage_Status)(nil),
		(*ConsoleServerMessage_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_minato_agent_v1_agent_proto_rawDesc), len(file_minato_agent_v1_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_minato_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_minato_agent_v1_agent_proto_depIdxs,
		EnumInfos:         file_minato_agent_v1_agent_proto_enumTypes,
		MessageInfos:      file_minato_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_minato_agent_v1_agent_proto = out.File
	file_minato_agent_v1_agent_proto_goTypes = nil
	file_minato_agent_v1_agent_proto_depIdxs = nil
}
