name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      go: ${{ steps.filter.outputs.go }}
      helm: ${{ steps.filter.outputs.helm }}
      proto: ${{ steps.filter.outputs.proto }}
      docker: ${{ steps.filter.outputs.docker }}
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Check for file changes
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: filter
        with:
          filters: |
            go:
              - '**.go'
              - 'go.mod'
              - 'go.sum'
              - 'Makefile'
            helm:
              - 'deploy/helm/**'
            proto:
              - 'proto/**'
              - 'buf.yaml'
              - 'buf.gen.yaml'
            docker:
              - 'Dockerfile'
              - '**/Dockerfile'
              - '.dockerignore'

  lint:
    needs: changes
    if: ${{ needs.changes.outputs.go == 'true' }}
    uses: ./.github/workflows/reusable-lint.yml
    with:
      check-generated: true

  unit-tests:
    needs: changes
    if: ${{ needs.changes.outputs.go == 'true' }}
    uses: ./.github/workflows/reusable-test.yml

  integration-tests:
    needs: changes
    if: ${{ needs.changes.outputs.go == 'true' }}
    uses: ./.github/workflows/reusable-integration-test.yml

  helm-check:
    needs: changes
    if: ${{ needs.changes.outputs.helm == 'true' }}
    uses: ./.github/workflows/reusable-helm.yml

  proto-check:
    needs: changes
    if: ${{ needs.changes.outputs.proto == 'true' }}
    uses: ./.github/workflows/reusable-proto.yml

  build-binaries:
    needs: [lint, unit-tests]
    if: ${{ needs.changes.outputs.go == 'true' }}
    uses: ./.github/workflows/reusable-build.yml

  build-images:
    needs: [lint, unit-tests]
    if: ${{ needs.changes.outputs.go == 'true' || needs.changes.outputs.docker == 'true' }}
    uses: ./.github/workflows/reusable-build-images.yml
