name: Reusable Test Workflow

on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        default: ubuntu-latest
      go-version-file:
        required: false
        type: string
        default: go.mod
      upload-coverage:
        required: false
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  test:
    name: Run Tests
    runs-on: ${{ inputs.runs-on }}
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version-file: ${{ inputs.go-version-file }}

      - name: Download dependencies
        run: go mod download

      - name: Run unit tests
        run: make test

      - name: Upload coverage
        if: inputs.upload-coverage
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4.6.0
        with:
          files: ./cover.out
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
