name: Reusable Integration Test Workflow

on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        default: ubuntu-latest
      go-version-file:
        required: false
        type: string
        default: go.mod

permissions:
  contents: read

jobs:
  integration:
    name: Run Integration Tests
    runs-on: ${{ inputs.runs-on }}
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version-file: ${{ inputs.go-version-file }}

      - name: Run integration tests
        run: make test-integration
